
import java.sql.Connection;
import java.sql.DriverManager;
import java.sql.PreparedStatement;
import java.sql.ResultSet;
import javax.swing.JOptionPane;

/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */

/**
 *
 * @author Mohamed_Abdeldaym
 */
public class AddEmp extends javax.swing.JFrame {

   private Connection con = null;
   private PreparedStatement ps = null;
   private ResultSet rs = null;
    
    java.util.Date BDate1;
    java.sql.Date mydate1;
    
     java.util.Date BDate2;
    java.sql.Date mydate2;
    public AddEmp() {
        initComponents();
        check_jobs(false);
    }
    
    private void check_jobs(boolean bool){
    
        l8.setVisible(bool);
        l9.setVisible(bool);
        et8.setVisible(bool);
        et9.setVisible(bool);
    
    }
    
   private void clear(){
       
       et1.setText("");
       et2.setText("");
       et3.setDate(BDate1);
       et4.setSelectedIndex(0);
       et5.setText("");
       et6.setText("");
       et7.setText("");
       et8.setText("");
       et9.setDate(BDate1);     
   }
   
 

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jPanel2 = new javax.swing.JPanel();
        jPanel3 = new javax.swing.JPanel();
        jLabel3 = new javax.swing.JLabel();
        jLabel4 = new javax.swing.JLabel();
        jLabel5 = new javax.swing.JLabel();
        jLabel6 = new javax.swing.JLabel();
        jLabel7 = new javax.swing.JLabel();
        jLabel8 = new javax.swing.JLabel();
        l8 = new javax.swing.JLabel();
        l9 = new javax.swing.JLabel();
        jLabel11 = new javax.swing.JLabel();
        et1 = new javax.swing.JTextField();
        et2 = new javax.swing.JTextField();
        et5 = new javax.swing.JTextField();
        et6 = new javax.swing.JTextField();
        et7 = new javax.swing.JTextField();
        et8 = new javax.swing.JTextField();
        et9 = new com.toedter.calendar.JDateChooser();
        et3 = new com.toedter.calendar.JDateChooser();
        et4 = new javax.swing.JComboBox<>();
        myButton6 = new MyButton();
        jLayeredPane1 = new javax.swing.JLayeredPane();
        jLabel1 = new javax.swing.JLabel();
        jLabel2 = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setUndecorated(true);

        jPanel2.setBorder(javax.swing.BorderFactory.createBevelBorder(javax.swing.border.BevelBorder.RAISED));

        jPanel3.setBorder(javax.swing.BorderFactory.createTitledBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(0, 0, 0)), "البيانات الاساسية", javax.swing.border.TitledBorder.RIGHT, javax.swing.border.TitledBorder.TOP, new java.awt.Font("Tahoma", 1, 18))); // NOI18N
        jPanel3.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jLabel3.setFont(new java.awt.Font("Tahoma", 1, 18)); // NOI18N
        jLabel3.setText("كود الموظف :");
        jPanel3.add(jLabel3, new org.netbeans.lib.awtextra.AbsoluteConstraints(495, 62, -1, -1));

        jLabel4.setFont(new java.awt.Font("Tahoma", 1, 18)); // NOI18N
        jLabel4.setText("اسم الموظف:");
        jPanel3.add(jLabel4, new org.netbeans.lib.awtextra.AbsoluteConstraints(495, 112, -1, -1));

        jLabel5.setFont(new java.awt.Font("Tahoma", 1, 18)); // NOI18N
        jLabel5.setText("تاريخ التعيين:");
        jPanel3.add(jLabel5, new org.netbeans.lib.awtextra.AbsoluteConstraints(495, 159, -1, -1));

        jLabel6.setFont(new java.awt.Font("Tahoma", 1, 18)); // NOI18N
        jLabel6.setText("الوظيفة:");
        jPanel3.add(jLabel6, new org.netbeans.lib.awtextra.AbsoluteConstraints(495, 208, -1, -1));

        jLabel7.setFont(new java.awt.Font("Tahoma", 1, 18)); // NOI18N
        jLabel7.setText("الموبيل:");
        jPanel3.add(jLabel7, new org.netbeans.lib.awtextra.AbsoluteConstraints(495, 262, -1, -1));

        jLabel8.setFont(new java.awt.Font("Tahoma", 1, 18)); // NOI18N
        jLabel8.setText("الرقم القومي:");
        jPanel3.add(jLabel8, new org.netbeans.lib.awtextra.AbsoluteConstraints(495, 315, -1, -1));

        l8.setFont(new java.awt.Font("Tahoma", 1, 18)); // NOI18N
        l8.setText("رقم الرخصة:");
        jPanel3.add(l8, new org.netbeans.lib.awtextra.AbsoluteConstraints(495, 411, -1, -1));

        l9.setFont(new java.awt.Font("Tahoma", 1, 18)); // NOI18N
        l9.setText("تاريخ انتهاء الرخصة:");
        jPanel3.add(l9, new org.netbeans.lib.awtextra.AbsoluteConstraints(495, 458, -1, -1));

        jLabel11.setFont(new java.awt.Font("Tahoma", 1, 18)); // NOI18N
        jLabel11.setText("الراتب الاساسي:");
        jPanel3.add(jLabel11, new org.netbeans.lib.awtextra.AbsoluteConstraints(495, 361, -1, -1));

        et1.setFont(new java.awt.Font("Tahoma", 1, 18)); // NOI18N
        et1.setHorizontalAlignment(javax.swing.JTextField.CENTER);
        jPanel3.add(et1, new org.netbeans.lib.awtextra.AbsoluteConstraints(120, 56, 365, 35));

        et2.setFont(new java.awt.Font("Tahoma", 1, 18)); // NOI18N
        et2.setHorizontalAlignment(javax.swing.JTextField.CENTER);
        jPanel3.add(et2, new org.netbeans.lib.awtextra.AbsoluteConstraints(120, 106, 365, 35));

        et5.setFont(new java.awt.Font("Tahoma", 1, 18)); // NOI18N
        et5.setHorizontalAlignment(javax.swing.JTextField.CENTER);
        et5.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                et5ActionPerformed(evt);
            }
        });
        jPanel3.add(et5, new org.netbeans.lib.awtextra.AbsoluteConstraints(120, 256, 365, 35));

        et6.setFont(new java.awt.Font("Tahoma", 1, 18)); // NOI18N
        et6.setHorizontalAlignment(javax.swing.JTextField.CENTER);
        et6.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                et6ActionPerformed(evt);
            }
        });
        jPanel3.add(et6, new org.netbeans.lib.awtextra.AbsoluteConstraints(120, 309, 365, 35));

        et7.setFont(new java.awt.Font("Tahoma", 1, 18)); // NOI18N
        et7.setHorizontalAlignment(javax.swing.JTextField.CENTER);
        et7.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                et7ActionPerformed(evt);
            }
        });
        jPanel3.add(et7, new org.netbeans.lib.awtextra.AbsoluteConstraints(120, 355, 365, 35));

        et8.setFont(new java.awt.Font("Tahoma", 1, 18)); // NOI18N
        et8.setHorizontalAlignment(javax.swing.JTextField.CENTER);
        et8.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                et8ActionPerformed(evt);
            }
        });
        jPanel3.add(et8, new org.netbeans.lib.awtextra.AbsoluteConstraints(120, 405, 365, 35));

        et9.setFont(new java.awt.Font("Tahoma", 1, 18)); // NOI18N
        jPanel3.add(et9, new org.netbeans.lib.awtextra.AbsoluteConstraints(120, 458, 365, 35));

        et3.setFont(new java.awt.Font("Tahoma", 1, 18)); // NOI18N
        jPanel3.add(et3, new org.netbeans.lib.awtextra.AbsoluteConstraints(120, 159, 365, 35));

        et4.setFont(new java.awt.Font("Tahoma", 1, 18)); // NOI18N
        et4.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "باريستا", "ستيور", "شيف", "طيار", "كابتن", "كاشير", "محاسب", "مدير مشتريات", "ويتر", "أخري" }));
        et4.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                et4ActionPerformed(evt);
            }
        });
        jPanel3.add(et4, new org.netbeans.lib.awtextra.AbsoluteConstraints(372, 210, 113, 35));

        myButton6.setForeground(new java.awt.Color(255, 255, 255));
        myButton6.setText("حفظ");
        myButton6.setBorderColor(new java.awt.Color(51, 102, 0));
        myButton6.setColor(new java.awt.Color(0, 102, 102));
        myButton6.setColorClick(new java.awt.Color(0, 153, 153));
        myButton6.setColorOver(new java.awt.Color(0, 102, 102));
        myButton6.setFont(new java.awt.Font("Tahoma", 1, 24)); // NOI18N
        myButton6.setRadius(40);
        myButton6.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                myButton6ActionPerformed(evt);
            }
        });
        jPanel3.add(myButton6, new org.netbeans.lib.awtextra.AbsoluteConstraints(20, 510, 168, 60));

        jLayeredPane1.setBackground(new java.awt.Color(0, 102, 102));
        jLayeredPane1.setOpaque(true);

        jLabel1.setBackground(new java.awt.Color(0, 51, 102));
        jLabel1.setFont(new java.awt.Font("Tahoma", 1, 24)); // NOI18N
        jLabel1.setForeground(new java.awt.Color(255, 255, 255));
        jLabel1.setText("X");
        jLabel1.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                jLabel1MouseClicked(evt);
            }
        });

        jLabel2.setFont(new java.awt.Font("Tahoma", 1, 20)); // NOI18N
        jLabel2.setForeground(new java.awt.Color(255, 255, 255));
        jLabel2.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabel2.setText("إضافة موظف جديد");

        jLayeredPane1.setLayer(jLabel1, javax.swing.JLayeredPane.DEFAULT_LAYER);
        jLayeredPane1.setLayer(jLabel2, javax.swing.JLayeredPane.DEFAULT_LAYER);

        javax.swing.GroupLayout jLayeredPane1Layout = new javax.swing.GroupLayout(jLayeredPane1);
        jLayeredPane1.setLayout(jLayeredPane1Layout);
        jLayeredPane1Layout.setHorizontalGroup(
            jLayeredPane1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jLayeredPane1Layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jLabel2)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addComponent(jLabel1, javax.swing.GroupLayout.PREFERRED_SIZE, 32, javax.swing.GroupLayout.PREFERRED_SIZE))
        );
        jLayeredPane1Layout.setVerticalGroup(
            jLayeredPane1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jLayeredPane1Layout.createSequentialGroup()
                .addGap(0, 0, Short.MAX_VALUE)
                .addGroup(jLayeredPane1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                    .addComponent(jLabel2, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(jLabel1, javax.swing.GroupLayout.DEFAULT_SIZE, 39, Short.MAX_VALUE)))
        );

        javax.swing.GroupLayout jPanel2Layout = new javax.swing.GroupLayout(jPanel2);
        jPanel2.setLayout(jPanel2Layout);
        jPanel2Layout.setHorizontalGroup(
            jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jLayeredPane1, javax.swing.GroupLayout.Alignment.TRAILING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel2Layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jPanel3, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addContainerGap())
        );
        jPanel2Layout.setVerticalGroup(
            jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel2Layout.createSequentialGroup()
                .addComponent(jLayeredPane1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jPanel3, javax.swing.GroupLayout.DEFAULT_SIZE, 581, Short.MAX_VALUE)
                .addContainerGap())
        );

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel2, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel2, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );

        pack();
        setLocationRelativeTo(null);
    }// </editor-fold>//GEN-END:initComponents

    private void jLabel1MouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jLabel1MouseClicked
        // TODO add your handling code here:
        dispose();
    }//GEN-LAST:event_jLabel1MouseClicked

    private void et5ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_et5ActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_et5ActionPerformed

    private void et6ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_et6ActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_et6ActionPerformed

    private void et7ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_et7ActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_et7ActionPerformed

    private void et8ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_et8ActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_et8ActionPerformed

    private void et4ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_et4ActionPerformed
        // TODO add your handling code here:
        String str = et4.getSelectedItem().toString();
        if (str.equals("طيار")) {

            check_jobs(true);

        } else {

            check_jobs(false);
        }
    }//GEN-LAST:event_et4ActionPerformed

    private void myButton6ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_myButton6ActionPerformed
        // TODO add your handling code here:
        
         // Add info
        if (et1.getText().equals("") || et2.getText().equals("") || et5.getText().equals("")
                || et6.getText().equals("") || et7.getText().equals("")) {
            JOptionPane.showMessageDialog(null, "Missing Data");
        } else {
            if (et5.getText().length() !=13 ) {
                JOptionPane.showMessageDialog(null, "Phone is incorrect");
            }else{
            BDate1 = et3.getDate();
            mydate1 = new java.sql.Date(BDate1.getTime());


            try {
                con = DriverManager.getConnection("jdbc:mysql://localhost/resturantmanagement", "root", "");
                String Quary = "INSERT INTO `employee`(`كود الموظف`, `اسم الموظف`, `تاريخ التعيين`, `الوظيفة`, `الموبيل`, `الرقم القومي`, `الراتب الاساسي`, `رقم الرخصة`, `تاريخ الانتهاء`) VALUES(?,?,?,?,?,?,?,?,?)";
                ps = con.prepareStatement(Quary);
                ps.setInt(1, Integer.valueOf(et1.getText()));
                ps.setString(2, et2.getText());
                ps.setDate(3, mydate1);
                ps.setString(4, et4.getSelectedItem().toString());
                ps.setString(5, et5.getText());
                ps.setString(6, et6.getText());
                ps.setInt(7, Integer.valueOf(et7.getText()));
                if(et4.getSelectedItem().toString().equals("طيار")){
                BDate2 = et9.getDate();
                mydate2 = new java.sql.Date(BDate2.getTime());
                ps.setString(8, et8.getText());
                ps.setDate(9, mydate2);}
                else{ 
                ps.setString(8, "");
                ps.setString(9,"");
                }
                if (ps.executeUpdate() > 0) {
                    JOptionPane.showMessageDialog(null, "New Employee Added Sucessful");
                    clear();
                }
            } catch (Exception e) {
                JOptionPane.showMessageDialog(this,e);
            }
                 }
        }
    }//GEN-LAST:event_myButton6ActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(AddEmp.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(AddEmp.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(AddEmp.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(AddEmp.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new AddEmp().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JTextField et1;
    private javax.swing.JTextField et2;
    private com.toedter.calendar.JDateChooser et3;
    private javax.swing.JComboBox<String> et4;
    private javax.swing.JTextField et5;
    private javax.swing.JTextField et6;
    private javax.swing.JTextField et7;
    private javax.swing.JTextField et8;
    private com.toedter.calendar.JDateChooser et9;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel11;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JLabel jLabel6;
    private javax.swing.JLabel jLabel7;
    private javax.swing.JLabel jLabel8;
    private javax.swing.JLayeredPane jLayeredPane1;
    private javax.swing.JPanel jPanel2;
    private javax.swing.JPanel jPanel3;
    private javax.swing.JLabel l8;
    private javax.swing.JLabel l9;
    private MyButton myButton6;
    // End of variables declaration//GEN-END:variables
}
