/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */

/**
 *
 * @author Mohamed_Abdeldaym
 */
public class Home1 extends javax.swing.JFrame {

    /**
     * Creates new form Home
     */
    public Home1() {
        initComponents();
        turnOff(false);
        turnOffHome(false);
        a1.setVisible(true);
        a2.setVisible(true);
    }
    
    public void turnOff(boolean x){ 
    a1.setVisible(x);
    a2.setVisible(x);
    b1.setVisible(x);
    b2.setVisible(x);
    b3.setVisible(x);
    c1.setVisible(x);
    c2.setVisible(x);
    c3.setVisible(x);
    c4.setVisible(x);
    c5.setVisible(x);
    }
    
    public void turnOffHome(boolean x){ 
    h1.setVisible(x);
    h2.setVisible(x);
    h3.setVisible(x);
    h4.setVisible(x);
    h5.setVisible(x);
    h6.setVisible(x);
    h7.setVisible(x);
    h8.setVisible(x);
    h9.setVisible(x);
    h10.setVisible(x);
    h11.setVisible(x);
    h12.setVisible(x);
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jButton1 = new javax.swing.JButton();
        jButton2 = new javax.swing.JButton();
        jButton3 = new javax.swing.JButton();
        jButton4 = new javax.swing.JButton();
        a1 = new MyButton();
        a2 = new MyButton();
        b1 = new MyButton();
        b2 = new MyButton();
        b3 = new MyButton();
        c1 = new MyButton();
        c2 = new MyButton();
        c4 = new MyButton();
        c3 = new MyButton();
        c5 = new MyButton();
        h1 = new MyButton();
        h2 = new MyButton();
        h3 = new MyButton();
        h4 = new MyButton();
        h5 = new MyButton();
        h6 = new MyButton();
        h7 = new MyButton();
        h8 = new MyButton();
        h10 = new MyButton();
        h9 = new MyButton();
        h11 = new MyButton();
        h12 = new MyButton();
        jLabel18 = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setUndecorated(true);
        getContentPane().setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jButton1.setBackground(new java.awt.Color(255, 255, 255));
        jButton1.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        jButton1.setForeground(new java.awt.Color(0, 0, 153));
        jButton1.setIcon(new javax.swing.ImageIcon(getClass().getResource("/images/h1.png"))); // NOI18N
        jButton1.setText("القائمة الرئيسية");
        jButton1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton1ActionPerformed(evt);
            }
        });
        getContentPane().add(jButton1, new org.netbeans.lib.awtextra.AbsoluteConstraints(80, 30, 280, 50));

        jButton2.setBackground(new java.awt.Color(255, 255, 255));
        jButton2.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        jButton2.setForeground(new java.awt.Color(0, 0, 153));
        jButton2.setIcon(new javax.swing.ImageIcon(getClass().getResource("/images/h2.png"))); // NOI18N
        jButton2.setText("اعدادات عامة");
        getContentPane().add(jButton2, new org.netbeans.lib.awtextra.AbsoluteConstraints(370, 30, 280, 50));

        jButton3.setBackground(new java.awt.Color(255, 255, 255));
        jButton3.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        jButton3.setForeground(new java.awt.Color(0, 0, 153));
        jButton3.setText("تغيير كلمة السر");
        getContentPane().add(jButton3, new org.netbeans.lib.awtextra.AbsoluteConstraints(660, 30, 280, 50));

        jButton4.setBackground(new java.awt.Color(255, 255, 255));
        jButton4.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        jButton4.setForeground(new java.awt.Color(0, 0, 153));
        jButton4.setText("خروج");
        jButton4.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton4ActionPerformed(evt);
            }
        });
        getContentPane().add(jButton4, new org.netbeans.lib.awtextra.AbsoluteConstraints(950, 30, 280, 50));

        a1.setForeground(new java.awt.Color(0, 255, 0));
        a1.setText("قسم المبيعات");
        a1.setBorderColor(new java.awt.Color(0, 102, 102));
        a1.setColor(new java.awt.Color(0, 102, 102));
        a1.setColorClick(new java.awt.Color(0, 153, 153));
        a1.setColorOver(new java.awt.Color(0, 102, 102));
        a1.setFont(new java.awt.Font("Tahoma", 1, 18)); // NOI18N
        a1.setRadius(20);
        a1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                a1ActionPerformed(evt);
            }
        });
        getContentPane().add(a1, new org.netbeans.lib.awtextra.AbsoluteConstraints(80, 150, 290, 70));

        a2.setForeground(new java.awt.Color(0, 255, 0));
        a2.setText("اعدادات الطباعة");
        a2.setBorderColor(new java.awt.Color(0, 102, 102));
        a2.setColor(new java.awt.Color(0, 102, 102));
        a2.setColorClick(new java.awt.Color(0, 153, 153));
        a2.setColorOver(new java.awt.Color(0, 102, 102));
        a2.setFont(new java.awt.Font("Tahoma", 1, 18)); // NOI18N
        a2.setRadius(20);
        getContentPane().add(a2, new org.netbeans.lib.awtextra.AbsoluteConstraints(80, 280, 290, 70));

        b1.setForeground(new java.awt.Color(0, 255, 0));
        b1.setText("بيانات");
        b1.setBorderColor(new java.awt.Color(0, 102, 102));
        b1.setColor(new java.awt.Color(0, 102, 102));
        b1.setColorClick(new java.awt.Color(0, 153, 153));
        b1.setColorOver(new java.awt.Color(0, 102, 102));
        b1.setFont(new java.awt.Font("Tahoma", 1, 18)); // NOI18N
        b1.setRadius(20);
        b1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                b1ActionPerformed(evt);
            }
        });
        getContentPane().add(b1, new org.netbeans.lib.awtextra.AbsoluteConstraints(80, 150, 290, 70));

        b2.setForeground(new java.awt.Color(0, 255, 0));
        b2.setText("حركات");
        b2.setBorderColor(new java.awt.Color(0, 102, 102));
        b2.setColor(new java.awt.Color(0, 102, 102));
        b2.setColorClick(new java.awt.Color(0, 153, 153));
        b2.setColorOver(new java.awt.Color(0, 102, 102));
        b2.setFont(new java.awt.Font("Tahoma", 1, 18)); // NOI18N
        b2.setRadius(20);
        b2.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                b2ActionPerformed(evt);
            }
        });
        getContentPane().add(b2, new org.netbeans.lib.awtextra.AbsoluteConstraints(80, 280, 290, 70));

        b3.setForeground(new java.awt.Color(0, 255, 0));
        b3.setText("تقارير");
        b3.setBorderColor(new java.awt.Color(0, 102, 102));
        b3.setColor(new java.awt.Color(0, 102, 102));
        b3.setColorClick(new java.awt.Color(0, 153, 153));
        b3.setColorOver(new java.awt.Color(0, 102, 102));
        b3.setFont(new java.awt.Font("Tahoma", 1, 18)); // NOI18N
        b3.setRadius(20);
        getContentPane().add(b3, new org.netbeans.lib.awtextra.AbsoluteConstraints(80, 410, 290, 70));

        c1.setForeground(new java.awt.Color(0, 255, 0));
        c1.setText("نقاط البيع");
        c1.setBorderColor(new java.awt.Color(0, 102, 102));
        c1.setColor(new java.awt.Color(0, 102, 102));
        c1.setColorClick(new java.awt.Color(0, 153, 153));
        c1.setColorOver(new java.awt.Color(0, 102, 102));
        c1.setFont(new java.awt.Font("Tahoma", 1, 18)); // NOI18N
        c1.setRadius(20);
        c1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                c1ActionPerformed(evt);
            }
        });
        getContentPane().add(c1, new org.netbeans.lib.awtextra.AbsoluteConstraints(80, 150, 290, 70));

        c2.setForeground(new java.awt.Color(0, 255, 0));
        c2.setText("اقفال وردية");
        c2.setBorderColor(new java.awt.Color(0, 102, 102));
        c2.setColor(new java.awt.Color(0, 102, 102));
        c2.setColorClick(new java.awt.Color(0, 153, 153));
        c2.setColorOver(new java.awt.Color(0, 102, 102));
        c2.setFont(new java.awt.Font("Tahoma", 1, 18)); // NOI18N
        c2.setRadius(20);
        getContentPane().add(c2, new org.netbeans.lib.awtextra.AbsoluteConstraints(80, 280, 290, 70));

        c4.setForeground(new java.awt.Color(0, 255, 0));
        c4.setText("<<");
        c4.setBorderColor(new java.awt.Color(0, 102, 102));
        c4.setColor(new java.awt.Color(0, 102, 102));
        c4.setColorClick(new java.awt.Color(0, 153, 153));
        c4.setColorOver(new java.awt.Color(0, 102, 102));
        c4.setFont(new java.awt.Font("Tahoma", 1, 24)); // NOI18N
        c4.setRadius(20);
        c4.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                c4ActionPerformed(evt);
            }
        });
        getContentPane().add(c4, new org.netbeans.lib.awtextra.AbsoluteConstraints(150, 640, 140, 60));

        c3.setForeground(new java.awt.Color(0, 255, 0));
        c3.setText("اوردرات اليوم");
        c3.setBorderColor(new java.awt.Color(0, 102, 102));
        c3.setColor(new java.awt.Color(0, 102, 102));
        c3.setColorClick(new java.awt.Color(0, 153, 153));
        c3.setColorOver(new java.awt.Color(0, 102, 102));
        c3.setFont(new java.awt.Font("Tahoma", 1, 18)); // NOI18N
        c3.setRadius(20);
        getContentPane().add(c3, new org.netbeans.lib.awtextra.AbsoluteConstraints(80, 410, 290, 70));

        c5.setForeground(new java.awt.Color(0, 255, 0));
        c5.setText("اقفال اليوم");
        c5.setBorderColor(new java.awt.Color(0, 102, 102));
        c5.setColor(new java.awt.Color(0, 102, 102));
        c5.setColorClick(new java.awt.Color(0, 153, 153));
        c5.setColorOver(new java.awt.Color(0, 102, 102));
        c5.setFont(new java.awt.Font("Tahoma", 1, 18)); // NOI18N
        c5.setRadius(20);
        getContentPane().add(c5, new org.netbeans.lib.awtextra.AbsoluteConstraints(80, 540, 290, 70));

        h1.setForeground(new java.awt.Color(0, 255, 0));
        h1.setText("الأصناف");
        h1.setBorderColor(new java.awt.Color(0, 102, 102));
        h1.setColor(new java.awt.Color(0, 102, 102));
        h1.setColorClick(new java.awt.Color(0, 153, 153));
        h1.setColorOver(new java.awt.Color(0, 102, 102));
        h1.setFont(new java.awt.Font("Tahoma", 1, 18)); // NOI18N
        h1.setRadius(50);
        h1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                h1ActionPerformed(evt);
            }
        });
        getContentPane().add(h1, new org.netbeans.lib.awtextra.AbsoluteConstraints(1040, 190, 180, 60));

        h2.setForeground(new java.awt.Color(0, 255, 0));
        h2.setText("الاقسام");
        h2.setBorderColor(new java.awt.Color(0, 102, 102));
        h2.setColor(new java.awt.Color(0, 102, 102));
        h2.setColorClick(new java.awt.Color(0, 153, 153));
        h2.setColorOver(new java.awt.Color(0, 102, 102));
        h2.setFont(new java.awt.Font("Tahoma", 1, 18)); // NOI18N
        h2.setRadius(50);
        h2.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                h2ActionPerformed(evt);
            }
        });
        getContentPane().add(h2, new org.netbeans.lib.awtextra.AbsoluteConstraints(850, 190, 180, 60));

        h3.setForeground(new java.awt.Color(0, 255, 0));
        h3.setText("الشاشات");
        h3.setBorderColor(new java.awt.Color(0, 102, 102));
        h3.setColor(new java.awt.Color(0, 102, 102));
        h3.setColorClick(new java.awt.Color(0, 153, 153));
        h3.setColorOver(new java.awt.Color(0, 102, 102));
        h3.setFont(new java.awt.Font("Tahoma", 1, 18)); // NOI18N
        h3.setRadius(50);
        getContentPane().add(h3, new org.netbeans.lib.awtextra.AbsoluteConstraints(660, 190, 180, 60));

        h4.setForeground(new java.awt.Color(0, 255, 0));
        h4.setText("الواحدات");
        h4.setBorderColor(new java.awt.Color(0, 102, 102));
        h4.setColor(new java.awt.Color(0, 102, 102));
        h4.setColorClick(new java.awt.Color(0, 153, 153));
        h4.setColorOver(new java.awt.Color(0, 102, 102));
        h4.setFont(new java.awt.Font("Tahoma", 1, 18)); // NOI18N
        h4.setRadius(50);
        getContentPane().add(h4, new org.netbeans.lib.awtextra.AbsoluteConstraints(470, 190, 180, 60));

        h5.setForeground(new java.awt.Color(0, 255, 0));
        h5.setText("المنافذ");
        h5.setBorderColor(new java.awt.Color(0, 102, 102));
        h5.setColor(new java.awt.Color(0, 102, 102));
        h5.setColorClick(new java.awt.Color(0, 153, 153));
        h5.setColorOver(new java.awt.Color(0, 102, 102));
        h5.setFont(new java.awt.Font("Tahoma", 1, 18)); // NOI18N
        h5.setRadius(50);
        getContentPane().add(h5, new org.netbeans.lib.awtextra.AbsoluteConstraints(280, 190, 180, 60));

        h6.setForeground(new java.awt.Color(0, 255, 0));
        h6.setText("------");
        h6.setBorderColor(new java.awt.Color(0, 102, 102));
        h6.setColor(new java.awt.Color(0, 102, 102));
        h6.setColorClick(new java.awt.Color(0, 153, 153));
        h6.setColorOver(new java.awt.Color(0, 102, 102));
        h6.setFont(new java.awt.Font("Tahoma", 1, 18)); // NOI18N
        h6.setRadius(50);
        getContentPane().add(h6, new org.netbeans.lib.awtextra.AbsoluteConstraints(90, 190, 180, 60));

        h7.setForeground(new java.awt.Color(0, 255, 0));
        h7.setText("المستخدمين");
        h7.setBorderColor(new java.awt.Color(0, 102, 102));
        h7.setColor(new java.awt.Color(0, 102, 102));
        h7.setColorClick(new java.awt.Color(0, 153, 153));
        h7.setColorOver(new java.awt.Color(0, 102, 102));
        h7.setFont(new java.awt.Font("Tahoma", 1, 18)); // NOI18N
        h7.setRadius(50);
        h7.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                h7ActionPerformed(evt);
            }
        });
        getContentPane().add(h7, new org.netbeans.lib.awtextra.AbsoluteConstraints(1040, 330, 180, 60));

        h8.setForeground(new java.awt.Color(0, 255, 0));
        h8.setText("الطيارين");
        h8.setBorderColor(new java.awt.Color(0, 102, 102));
        h8.setColor(new java.awt.Color(0, 102, 102));
        h8.setColorClick(new java.awt.Color(0, 153, 153));
        h8.setColorOver(new java.awt.Color(0, 102, 102));
        h8.setFont(new java.awt.Font("Tahoma", 1, 18)); // NOI18N
        h8.setRadius(50);
        h8.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                h8ActionPerformed(evt);
            }
        });
        getContentPane().add(h8, new org.netbeans.lib.awtextra.AbsoluteConstraints(850, 330, 180, 60));

        h10.setForeground(new java.awt.Color(0, 255, 0));
        h10.setText("الويتر");
        h10.setBorderColor(new java.awt.Color(0, 102, 102));
        h10.setColor(new java.awt.Color(0, 102, 102));
        h10.setColorClick(new java.awt.Color(0, 153, 153));
        h10.setColorOver(new java.awt.Color(0, 102, 102));
        h10.setFont(new java.awt.Font("Tahoma", 1, 18)); // NOI18N
        h10.setRadius(50);
        h10.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                h10ActionPerformed(evt);
            }
        });
        getContentPane().add(h10, new org.netbeans.lib.awtextra.AbsoluteConstraints(470, 330, 180, 60));

        h9.setForeground(new java.awt.Color(0, 255, 0));
        h9.setText("المناطق");
        h9.setBorderColor(new java.awt.Color(0, 102, 102));
        h9.setColor(new java.awt.Color(0, 102, 102));
        h9.setColorClick(new java.awt.Color(0, 153, 153));
        h9.setColorOver(new java.awt.Color(0, 102, 102));
        h9.setFont(new java.awt.Font("Tahoma", 1, 18)); // NOI18N
        h9.setRadius(50);
        h9.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                h9ActionPerformed(evt);
            }
        });
        getContentPane().add(h9, new org.netbeans.lib.awtextra.AbsoluteConstraints(660, 330, 180, 60));

        h11.setForeground(new java.awt.Color(0, 255, 0));
        h11.setText("الصالات");
        h11.setBorderColor(new java.awt.Color(0, 102, 102));
        h11.setColor(new java.awt.Color(0, 102, 102));
        h11.setColorClick(new java.awt.Color(0, 153, 153));
        h11.setColorOver(new java.awt.Color(0, 102, 102));
        h11.setFont(new java.awt.Font("Tahoma", 1, 18)); // NOI18N
        h11.setRadius(50);
        h11.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                h11ActionPerformed(evt);
            }
        });
        getContentPane().add(h11, new org.netbeans.lib.awtextra.AbsoluteConstraints(280, 330, 180, 60));

        h12.setForeground(new java.awt.Color(0, 255, 0));
        h12.setText("الترابيزات");
        h12.setBorderColor(new java.awt.Color(0, 102, 102));
        h12.setColor(new java.awt.Color(0, 102, 102));
        h12.setColorClick(new java.awt.Color(0, 153, 153));
        h12.setColorOver(new java.awt.Color(0, 102, 102));
        h12.setFont(new java.awt.Font("Tahoma", 1, 18)); // NOI18N
        h12.setRadius(50);
        getContentPane().add(h12, new org.netbeans.lib.awtextra.AbsoluteConstraints(90, 330, 180, 60));

        jLabel18.setIcon(new javax.swing.ImageIcon(getClass().getResource("/images/home-background-image.png"))); // NOI18N
        getContentPane().add(jLabel18, new org.netbeans.lib.awtextra.AbsoluteConstraints(-4, -2, 1366, 768));

        pack();
        setLocationRelativeTo(null);
    }// </editor-fold>//GEN-END:initComponents

    private void jButton4ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton4ActionPerformed
        // TODO add your handling code here:
        dispose();
    }//GEN-LAST:event_jButton4ActionPerformed

    private void jButton1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton1ActionPerformed
        // TODO add your handling code here:
        turnOff(false);
        turnOffHome(false);
        a1.setVisible(true);
        a2.setVisible(true);

    }//GEN-LAST:event_jButton1ActionPerformed

    private void a1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_a1ActionPerformed
        // TODO add your handling code here:
      turnOff(false);
      b1.setVisible(true);
      b2.setVisible(true);
      b3.setVisible(true);

    }//GEN-LAST:event_a1ActionPerformed

    private void b1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_b1ActionPerformed
        // TODO add your handling code here:
        turnOff(false);
        turnOffHome(true);
    }//GEN-LAST:event_b1ActionPerformed

    private void b2ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_b2ActionPerformed
        // TODO add your handling code here:
        turnOff(false);
        c1.setVisible(true);
        c2.setVisible(true);
        c3.setVisible(true);
        c4.setVisible(true);
        c5.setVisible(true);
    }//GEN-LAST:event_b2ActionPerformed

    private void c1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_c1ActionPerformed
        // TODO add your handling code here:
        new ScreenSalles().setVisible(true);
    }//GEN-LAST:event_c1ActionPerformed

    private void c4ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_c4ActionPerformed
        // TODO add your handling code here:
        turnOff(false);
        turnOffHome(false);
        b1.setVisible(true);
        b2.setVisible(true);
        b3.setVisible(true);
    }//GEN-LAST:event_c4ActionPerformed

    private void h7ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_h7ActionPerformed
        // TODO add your handling code here:
        new Screen_Users().setVisible(true);
    }//GEN-LAST:event_h7ActionPerformed

    private void h1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_h1ActionPerformed
        // TODO add your handling code here:
        new categories().setVisible(true);
    }//GEN-LAST:event_h1ActionPerformed

    private void h2ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_h2ActionPerformed
        // TODO add your handling code here:
        new Screen_depart().setVisible(true);
    }//GEN-LAST:event_h2ActionPerformed

    private void h8ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_h8ActionPerformed
        // TODO add your handling code here:
        new Screen_pilot().setVisible(true);
    }//GEN-LAST:event_h8ActionPerformed

    private void h9ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_h9ActionPerformed
        // TODO add your handling code here:
        new Screen_Regions().setVisible(true);
    }//GEN-LAST:event_h9ActionPerformed

    private void h10ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_h10ActionPerformed
        // TODO add your handling code here:
        new Screen_Waiter().setVisible(true);
    }//GEN-LAST:event_h10ActionPerformed

    private void h11ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_h11ActionPerformed
        // TODO add your handling code here:
        new NumberOfHalls().setVisible(true);
    }//GEN-LAST:event_h11ActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(Home.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(Home.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(Home.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(Home.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new Home1().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private MyButton a1;
    private MyButton a2;
    private MyButton b1;
    private MyButton b2;
    private MyButton b3;
    private MyButton c1;
    private MyButton c2;
    private MyButton c3;
    private MyButton c4;
    private MyButton c5;
    private MyButton h1;
    private MyButton h10;
    private MyButton h11;
    private MyButton h12;
    private MyButton h2;
    private MyButton h3;
    private MyButton h4;
    private MyButton h5;
    private MyButton h6;
    private MyButton h7;
    private MyButton h8;
    private MyButton h9;
    private javax.swing.JButton jButton1;
    private javax.swing.JButton jButton2;
    private javax.swing.JButton jButton3;
    private javax.swing.JButton jButton4;
    private javax.swing.JLabel jLabel18;
    // End of variables declaration//GEN-END:variables
}
