/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */

/**
 *
 * @author Mohamed_Abdeldaym
 */
public class Home extends javax.swing.JFrame {

    /**
     * Creates new form Home
     */
    public Home() {
        initComponents();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jButton1 = new javax.swing.JButton();
        jButton2 = new javax.swing.JButton();
        jButton3 = new javax.swing.JButton();
        jButton4 = new javax.swing.JButton();
        h1 = new MyButton();
        h2 = new MyButton();
        h3 = new MyButton();
        h4 = new MyButton();
        h5 = new MyButton();
        h6 = new MyButton();
        h7 = new MyButton();
        h8 = new MyButton();
        h10 = new MyButton();
        h9 = new MyButton();
        h11 = new MyButton();
        h12 = new MyButton();
        jLabel18 = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setUndecorated(true);
        getContentPane().setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jButton1.setBackground(new java.awt.Color(255, 255, 255));
        jButton1.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        jButton1.setForeground(new java.awt.Color(0, 0, 153));
        jButton1.setIcon(new javax.swing.ImageIcon(getClass().getResource("/images/h1.png"))); // NOI18N
        jButton1.setText("القائمة الرئيسية");
        jButton1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton1ActionPerformed(evt);
            }
        });
        getContentPane().add(jButton1, new org.netbeans.lib.awtextra.AbsoluteConstraints(80, 30, 280, 50));

        jButton2.setBackground(new java.awt.Color(255, 255, 255));
        jButton2.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        jButton2.setForeground(new java.awt.Color(0, 0, 153));
        jButton2.setIcon(new javax.swing.ImageIcon(getClass().getResource("/images/h2.png"))); // NOI18N
        jButton2.setText("اعدادات عامة");
        getContentPane().add(jButton2, new org.netbeans.lib.awtextra.AbsoluteConstraints(370, 30, 280, 50));

        jButton3.setBackground(new java.awt.Color(255, 255, 255));
        jButton3.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        jButton3.setForeground(new java.awt.Color(0, 0, 153));
        jButton3.setText("تغيير كلمة السر");
        getContentPane().add(jButton3, new org.netbeans.lib.awtextra.AbsoluteConstraints(660, 30, 280, 50));

        jButton4.setBackground(new java.awt.Color(255, 255, 255));
        jButton4.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        jButton4.setForeground(new java.awt.Color(0, 0, 153));
        jButton4.setText("خروج");
        jButton4.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton4ActionPerformed(evt);
            }
        });
        getContentPane().add(jButton4, new org.netbeans.lib.awtextra.AbsoluteConstraints(950, 30, 280, 50));

        h1.setForeground(new java.awt.Color(0, 255, 0));
        h1.setText("الأصناف");
        h1.setBorderColor(new java.awt.Color(0, 102, 102));
        h1.setColor(new java.awt.Color(0, 102, 102));
        h1.setColorClick(new java.awt.Color(0, 153, 153));
        h1.setColorOver(new java.awt.Color(0, 102, 102));
        h1.setFont(new java.awt.Font("Tahoma", 1, 18)); // NOI18N
        h1.setRadius(50);
        getContentPane().add(h1, new org.netbeans.lib.awtextra.AbsoluteConstraints(1040, 190, 180, 60));

        h2.setForeground(new java.awt.Color(0, 255, 0));
        h2.setText("الاقسام");
        h2.setBorderColor(new java.awt.Color(0, 102, 102));
        h2.setColor(new java.awt.Color(0, 102, 102));
        h2.setColorClick(new java.awt.Color(0, 153, 153));
        h2.setColorOver(new java.awt.Color(0, 102, 102));
        h2.setFont(new java.awt.Font("Tahoma", 1, 18)); // NOI18N
        h2.setRadius(50);
        getContentPane().add(h2, new org.netbeans.lib.awtextra.AbsoluteConstraints(850, 190, 180, 60));

        h3.setForeground(new java.awt.Color(0, 255, 0));
        h3.setText("الشاشات");
        h3.setBorderColor(new java.awt.Color(0, 102, 102));
        h3.setColor(new java.awt.Color(0, 102, 102));
        h3.setColorClick(new java.awt.Color(0, 153, 153));
        h3.setColorOver(new java.awt.Color(0, 102, 102));
        h3.setFont(new java.awt.Font("Tahoma", 1, 18)); // NOI18N
        h3.setRadius(50);
        getContentPane().add(h3, new org.netbeans.lib.awtextra.AbsoluteConstraints(660, 190, 180, 60));

        h4.setForeground(new java.awt.Color(0, 255, 0));
        h4.setText("الواحدات");
        h4.setBorderColor(new java.awt.Color(0, 102, 102));
        h4.setColor(new java.awt.Color(0, 102, 102));
        h4.setColorClick(new java.awt.Color(0, 153, 153));
        h4.setColorOver(new java.awt.Color(0, 102, 102));
        h4.setFont(new java.awt.Font("Tahoma", 1, 18)); // NOI18N
        h4.setRadius(50);
        getContentPane().add(h4, new org.netbeans.lib.awtextra.AbsoluteConstraints(470, 190, 180, 60));

        h5.setForeground(new java.awt.Color(0, 255, 0));
        h5.setText("المنافذ");
        h5.setBorderColor(new java.awt.Color(0, 102, 102));
        h5.setColor(new java.awt.Color(0, 102, 102));
        h5.setColorClick(new java.awt.Color(0, 153, 153));
        h5.setColorOver(new java.awt.Color(0, 102, 102));
        h5.setFont(new java.awt.Font("Tahoma", 1, 18)); // NOI18N
        h5.setRadius(50);
        getContentPane().add(h5, new org.netbeans.lib.awtextra.AbsoluteConstraints(280, 190, 180, 60));

        h6.setForeground(new java.awt.Color(0, 255, 0));
        h6.setText("------");
        h6.setBorderColor(new java.awt.Color(0, 102, 102));
        h6.setColor(new java.awt.Color(0, 102, 102));
        h6.setColorClick(new java.awt.Color(0, 153, 153));
        h6.setColorOver(new java.awt.Color(0, 102, 102));
        h6.setFont(new java.awt.Font("Tahoma", 1, 18)); // NOI18N
        h6.setRadius(50);
        getContentPane().add(h6, new org.netbeans.lib.awtextra.AbsoluteConstraints(90, 190, 180, 60));

        h7.setForeground(new java.awt.Color(0, 255, 0));
        h7.setText("المستخدمين");
        h7.setBorderColor(new java.awt.Color(0, 102, 102));
        h7.setColor(new java.awt.Color(0, 102, 102));
        h7.setColorClick(new java.awt.Color(0, 153, 153));
        h7.setColorOver(new java.awt.Color(0, 102, 102));
        h7.setFont(new java.awt.Font("Tahoma", 1, 18)); // NOI18N
        h7.setRadius(50);
        h7.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                h7ActionPerformed(evt);
            }
        });
        getContentPane().add(h7, new org.netbeans.lib.awtextra.AbsoluteConstraints(1040, 330, 180, 60));

        h8.setForeground(new java.awt.Color(0, 255, 0));
        h8.setText("الطيارين");
        h8.setBorderColor(new java.awt.Color(0, 102, 102));
        h8.setColor(new java.awt.Color(0, 102, 102));
        h8.setColorClick(new java.awt.Color(0, 153, 153));
        h8.setColorOver(new java.awt.Color(0, 102, 102));
        h8.setFont(new java.awt.Font("Tahoma", 1, 18)); // NOI18N
        h8.setRadius(50);
        getContentPane().add(h8, new org.netbeans.lib.awtextra.AbsoluteConstraints(850, 330, 180, 60));

        h10.setForeground(new java.awt.Color(0, 255, 0));
        h10.setText("الويتر");
        h10.setBorderColor(new java.awt.Color(0, 102, 102));
        h10.setColor(new java.awt.Color(0, 102, 102));
        h10.setColorClick(new java.awt.Color(0, 153, 153));
        h10.setColorOver(new java.awt.Color(0, 102, 102));
        h10.setFont(new java.awt.Font("Tahoma", 1, 18)); // NOI18N
        h10.setRadius(50);
        getContentPane().add(h10, new org.netbeans.lib.awtextra.AbsoluteConstraints(470, 330, 180, 60));

        h9.setForeground(new java.awt.Color(0, 255, 0));
        h9.setText("المناطق");
        h9.setBorderColor(new java.awt.Color(0, 102, 102));
        h9.setColor(new java.awt.Color(0, 102, 102));
        h9.setColorClick(new java.awt.Color(0, 153, 153));
        h9.setColorOver(new java.awt.Color(0, 102, 102));
        h9.setFont(new java.awt.Font("Tahoma", 1, 18)); // NOI18N
        h9.setRadius(50);
        getContentPane().add(h9, new org.netbeans.lib.awtextra.AbsoluteConstraints(660, 330, 180, 60));

        h11.setForeground(new java.awt.Color(0, 255, 0));
        h11.setText("الصالات");
        h11.setBorderColor(new java.awt.Color(0, 102, 102));
        h11.setColor(new java.awt.Color(0, 102, 102));
        h11.setColorClick(new java.awt.Color(0, 153, 153));
        h11.setColorOver(new java.awt.Color(0, 102, 102));
        h11.setFont(new java.awt.Font("Tahoma", 1, 18)); // NOI18N
        h11.setRadius(50);
        getContentPane().add(h11, new org.netbeans.lib.awtextra.AbsoluteConstraints(280, 330, 180, 60));

        h12.setForeground(new java.awt.Color(0, 255, 0));
        h12.setText("الترابيزات");
        h12.setBorderColor(new java.awt.Color(0, 102, 102));
        h12.setColor(new java.awt.Color(0, 102, 102));
        h12.setColorClick(new java.awt.Color(0, 153, 153));
        h12.setColorOver(new java.awt.Color(0, 102, 102));
        h12.setFont(new java.awt.Font("Tahoma", 1, 18)); // NOI18N
        h12.setRadius(50);
        getContentPane().add(h12, new org.netbeans.lib.awtextra.AbsoluteConstraints(90, 330, 180, 60));

        jLabel18.setIcon(new javax.swing.ImageIcon(getClass().getResource("/images/home-background-image.png"))); // NOI18N
        getContentPane().add(jLabel18, new org.netbeans.lib.awtextra.AbsoluteConstraints(-4, -2, 1366, 768));

        pack();
        setLocationRelativeTo(null);
    }// </editor-fold>//GEN-END:initComponents

    private void jButton4ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton4ActionPerformed
        // TODO add your handling code here:
        dispose();
    }//GEN-LAST:event_jButton4ActionPerformed

    private void h7ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_h7ActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_h7ActionPerformed

    private void jButton1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton1ActionPerformed
        // TODO add your handling code here:
        new Home1().setVisible(true);
        dispose();
    }//GEN-LAST:event_jButton1ActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(Home.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(Home.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(Home.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(Home.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new Home().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private MyButton h1;
    private MyButton h10;
    private MyButton h11;
    private MyButton h12;
    private MyButton h2;
    private MyButton h3;
    private MyButton h4;
    private MyButton h5;
    private MyButton h6;
    private MyButton h7;
    private MyButton h8;
    private MyButton h9;
    private javax.swing.JButton jButton1;
    private javax.swing.JButton jButton2;
    private javax.swing.JButton jButton3;
    private javax.swing.JButton jButton4;
    private javax.swing.JLabel jLabel18;
    // End of variables declaration//GEN-END:variables
}
