

import java.sql.*;
import javax.swing.JOptionPane;
import net.proteanit.sql.DbUtils;


/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */

/**
 *
 * @author Mohamed_Abdeldaym
 */
public class Order_Delivery extends javax.swing.JFrame {


    private Connection con = null;
    private PreparedStatement ps = null;
    private ResultSet rs = null;
    
    
    public Order_Delivery() {
        initComponents();
        new client().table_setting(this.jTable1);
    }
    
   
    


    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        myButton11 = new MyButton();
        myButton12 = new MyButton();
        myButton13 = new MyButton();
        myButton15 = new MyButton();
        myButton17 = new MyButton();
        jScrollPane2 = new javax.swing.JScrollPane();
        jTable1 = new javax.swing.JTable();
        dt8 = new javax.swing.JTextField();
        jLabel5 = new javax.swing.JLabel();
        jCheckBox8 = new javax.swing.JCheckBox();
        dt12 = new javax.swing.JTextField();
        dt13 = new javax.swing.JTextField();
        dt16 = new javax.swing.JTextField();
        dt17 = new javax.swing.JTextField();
        jCheckBox9 = new javax.swing.JCheckBox();
        jCheckBox10 = new javax.swing.JCheckBox();
        jCheckBox11 = new javax.swing.JCheckBox();
        jCheckBox12 = new javax.swing.JCheckBox();
        jCheckBox13 = new javax.swing.JCheckBox();
        jLabel18 = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setUndecorated(true);
        getContentPane().setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        myButton11.setForeground(new java.awt.Color(0, 255, 0));
        myButton11.setText("خروج");
        myButton11.setBorderColor(new java.awt.Color(0, 102, 102));
        myButton11.setColor(new java.awt.Color(0, 102, 102));
        myButton11.setColorClick(new java.awt.Color(0, 153, 153));
        myButton11.setColorOver(new java.awt.Color(0, 102, 102));
        myButton11.setFont(new java.awt.Font("Tahoma", 1, 18)); // NOI18N
        myButton11.setRadius(15);
        myButton11.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                myButton11ActionPerformed(evt);
            }
        });
        getContentPane().add(myButton11, new org.netbeans.lib.awtextra.AbsoluteConstraints(1140, 30, 190, 70));

        myButton12.setForeground(new java.awt.Color(0, 255, 0));
        myButton12.setText("اوردرات تنتظر التسليم");
        myButton12.setBorderColor(new java.awt.Color(0, 102, 102));
        myButton12.setColor(new java.awt.Color(0, 102, 102));
        myButton12.setColorClick(new java.awt.Color(0, 153, 153));
        myButton12.setColorOver(new java.awt.Color(0, 102, 102));
        myButton12.setFont(new java.awt.Font("Tahoma", 1, 18)); // NOI18N
        myButton12.setRadius(15);
        myButton12.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                myButton12ActionPerformed(evt);
            }
        });
        getContentPane().add(myButton12, new org.netbeans.lib.awtextra.AbsoluteConstraints(520, 30, 220, 70));

        myButton13.setForeground(new java.awt.Color(0, 255, 0));
        myButton13.setText("طباعة البون");
        myButton13.setBorderColor(new java.awt.Color(0, 102, 102));
        myButton13.setColor(new java.awt.Color(0, 102, 102));
        myButton13.setColorClick(new java.awt.Color(0, 153, 153));
        myButton13.setColorOver(new java.awt.Color(0, 102, 102));
        myButton13.setFont(new java.awt.Font("Tahoma", 1, 18)); // NOI18N
        myButton13.setRadius(15);
        myButton13.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                myButton13ActionPerformed(evt);
            }
        });
        getContentPane().add(myButton13, new org.netbeans.lib.awtextra.AbsoluteConstraints(930, 30, 200, 70));

        myButton15.setForeground(new java.awt.Color(0, 255, 0));
        myButton15.setText("حساب الطيار");
        myButton15.setBorderColor(new java.awt.Color(0, 102, 102));
        myButton15.setColor(new java.awt.Color(0, 102, 102));
        myButton15.setColorClick(new java.awt.Color(0, 153, 153));
        myButton15.setColorOver(new java.awt.Color(0, 102, 102));
        myButton15.setFont(new java.awt.Font("Tahoma", 1, 18)); // NOI18N
        myButton15.setRadius(15);
        myButton15.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                myButton15ActionPerformed(evt);
            }
        });
        getContentPane().add(myButton15, new org.netbeans.lib.awtextra.AbsoluteConstraints(750, 30, 170, 70));

        myButton17.setForeground(new java.awt.Color(0, 255, 0));
        myButton17.setText("انهاء حساب الطيار");
        myButton17.setBorderColor(new java.awt.Color(0, 102, 102));
        myButton17.setColor(new java.awt.Color(0, 102, 102));
        myButton17.setColorClick(new java.awt.Color(0, 153, 153));
        myButton17.setColorOver(new java.awt.Color(0, 102, 102));
        myButton17.setFont(new java.awt.Font("Tahoma", 1, 18)); // NOI18N
        myButton17.setRadius(15);
        myButton17.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                myButton17ActionPerformed(evt);
            }
        });
        getContentPane().add(myButton17, new org.netbeans.lib.awtextra.AbsoluteConstraints(320, 30, 190, 70));

        jTable1.setFont(new java.awt.Font("Tahoma", 1, 18)); // NOI18N
        jTable1.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {

            },
            new String [] {
                "تاريخ انهاء التجهيز", "المنطقة", "الشقة", "الدور", "الشارع", "المنزل", "الصافي", "التاريخ"
            }
        ) {
            boolean[] canEdit = new boolean [] {
                false, false, false, false, false, false, false, false
            };

            public boolean isCellEditable(int rowIndex, int columnIndex) {
                return canEdit [columnIndex];
            }
        });
        jScrollPane2.setViewportView(jTable1);

        getContentPane().add(jScrollPane2, new org.netbeans.lib.awtextra.AbsoluteConstraints(320, 150, 1040, 580));

        dt8.setFont(new java.awt.Font("Tahoma", 1, 18)); // NOI18N
        dt8.setHorizontalAlignment(javax.swing.JTextField.CENTER);
        getContentPane().add(dt8, new org.netbeans.lib.awtextra.AbsoluteConstraints(20, 150, 240, 30));

        jLabel5.setFont(new java.awt.Font("Tahoma", 1, 18)); // NOI18N
        jLabel5.setForeground(new java.awt.Color(255, 255, 255));
        jLabel5.setText("تحديد/الغاء الكل");
        getContentPane().add(jLabel5, new org.netbeans.lib.awtextra.AbsoluteConstraints(370, 110, -1, 30));

        jCheckBox8.setFont(new java.awt.Font("Tahoma", 0, 48)); // NOI18N
        jCheckBox8.setHorizontalAlignment(javax.swing.SwingConstants.RIGHT);
        jCheckBox8.setOpaque(false);
        getContentPane().add(jCheckBox8, new org.netbeans.lib.awtextra.AbsoluteConstraints(260, 150, 30, 30));

        dt12.setFont(new java.awt.Font("Tahoma", 1, 18)); // NOI18N
        dt12.setHorizontalAlignment(javax.swing.JTextField.CENTER);
        getContentPane().add(dt12, new org.netbeans.lib.awtextra.AbsoluteConstraints(20, 30, 240, 30));

        dt13.setFont(new java.awt.Font("Tahoma", 1, 18)); // NOI18N
        dt13.setHorizontalAlignment(javax.swing.JTextField.CENTER);
        getContentPane().add(dt13, new org.netbeans.lib.awtextra.AbsoluteConstraints(20, 60, 240, 30));

        dt16.setFont(new java.awt.Font("Tahoma", 1, 18)); // NOI18N
        dt16.setHorizontalAlignment(javax.swing.JTextField.CENTER);
        getContentPane().add(dt16, new org.netbeans.lib.awtextra.AbsoluteConstraints(20, 90, 240, 30));

        dt17.setFont(new java.awt.Font("Tahoma", 1, 18)); // NOI18N
        dt17.setHorizontalAlignment(javax.swing.JTextField.CENTER);
        getContentPane().add(dt17, new org.netbeans.lib.awtextra.AbsoluteConstraints(20, 120, 240, 30));

        jCheckBox9.setFont(new java.awt.Font("Tahoma", 0, 48)); // NOI18N
        jCheckBox9.setHorizontalAlignment(javax.swing.SwingConstants.RIGHT);
        jCheckBox9.setOpaque(false);
        getContentPane().add(jCheckBox9, new org.netbeans.lib.awtextra.AbsoluteConstraints(330, 110, 30, 30));

        jCheckBox10.setFont(new java.awt.Font("Tahoma", 0, 48)); // NOI18N
        jCheckBox10.setHorizontalAlignment(javax.swing.SwingConstants.RIGHT);
        jCheckBox10.setOpaque(false);
        getContentPane().add(jCheckBox10, new org.netbeans.lib.awtextra.AbsoluteConstraints(260, 30, 30, 30));

        jCheckBox11.setFont(new java.awt.Font("Tahoma", 0, 48)); // NOI18N
        jCheckBox11.setHorizontalAlignment(javax.swing.SwingConstants.RIGHT);
        jCheckBox11.setOpaque(false);
        getContentPane().add(jCheckBox11, new org.netbeans.lib.awtextra.AbsoluteConstraints(260, 60, 30, 30));

        jCheckBox12.setFont(new java.awt.Font("Tahoma", 0, 48)); // NOI18N
        jCheckBox12.setHorizontalAlignment(javax.swing.SwingConstants.RIGHT);
        jCheckBox12.setOpaque(false);
        getContentPane().add(jCheckBox12, new org.netbeans.lib.awtextra.AbsoluteConstraints(260, 90, 30, 30));

        jCheckBox13.setFont(new java.awt.Font("Tahoma", 0, 48)); // NOI18N
        jCheckBox13.setHorizontalAlignment(javax.swing.SwingConstants.RIGHT);
        jCheckBox13.setOpaque(false);
        getContentPane().add(jCheckBox13, new org.netbeans.lib.awtextra.AbsoluteConstraints(260, 120, 30, 30));

        jLabel18.setIcon(new javax.swing.ImageIcon(getClass().getResource("/images/home-background-image.png"))); // NOI18N
        getContentPane().add(jLabel18, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 0, -1, -1));

        pack();
        setLocationRelativeTo(null);
    }// </editor-fold>//GEN-END:initComponents

    private void myButton11ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_myButton11ActionPerformed
        // TODO add your handling code here:
        dispose();
    }//GEN-LAST:event_myButton11ActionPerformed

    private void myButton12ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_myButton12ActionPerformed
        // TODO add your handling code here:
        
    
    }//GEN-LAST:event_myButton12ActionPerformed

    private void myButton13ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_myButton13ActionPerformed
        // TODO add your handling code here:
        
            // Add
       
    }//GEN-LAST:event_myButton13ActionPerformed

    private void myButton15ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_myButton15ActionPerformed
        // TODO add your handling code here:

    }//GEN-LAST:event_myButton15ActionPerformed

    private void myButton17ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_myButton17ActionPerformed
        // TODO add your handling code here:
        
    }//GEN-LAST:event_myButton17ActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(categories.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(categories.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(categories.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(categories.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new Order_Delivery().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JTextField dt12;
    private javax.swing.JTextField dt13;
    private javax.swing.JTextField dt16;
    private javax.swing.JTextField dt17;
    private javax.swing.JTextField dt8;
    private javax.swing.JCheckBox jCheckBox10;
    private javax.swing.JCheckBox jCheckBox11;
    private javax.swing.JCheckBox jCheckBox12;
    private javax.swing.JCheckBox jCheckBox13;
    private javax.swing.JCheckBox jCheckBox8;
    private javax.swing.JCheckBox jCheckBox9;
    private javax.swing.JLabel jLabel18;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JScrollPane jScrollPane2;
    private javax.swing.JTable jTable1;
    private MyButton myButton11;
    private MyButton myButton12;
    private MyButton myButton13;
    private MyButton myButton15;
    private MyButton myButton17;
    // End of variables declaration//GEN-END:variables
}
