

import java.awt.event.ActionEvent;
import java.awt.event.ActionListener;
import java.sql.Connection;
import java.sql.DriverManager;
import java.sql.PreparedStatement;
import java.sql.ResultSet;
import java.sql.ResultSetMetaData;
import java.sql.Statement;
import java.text.SimpleDateFormat;
import java.util.Date;
import javax.swing.JOptionPane;
import javax.swing.Timer;
import javax.swing.table.DefaultTableModel;
import net.proteanit.sql.DbUtils;

/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */

/**
 *
 * @author Mohamed_Abdeldaym
 */
public class ScreenSalles extends javax.swing.JFrame {

    private Connection con = null;
    private PreparedStatement ps = null;
    private ResultSet rs = null;
    DefaultTableModel model;
    
    int qty=0;
    int price=0;
    int total = 0;
    String name="";
    
    public ScreenSalles() {
        initComponents();
        Fill_tableDepart();
        new client().table_setting(this.order_table);
        new client().table_setting(this.table_depart);
        new client().table_setting(this.categort_table);
       
        hist();
        
        times();
    }
    
    public void hist(){
    
        Date d = new Date();
        SimpleDateFormat df = new SimpleDateFormat("yyyy-MM-dd");
        String str = df.format(d);
        history.setText(str);  
    }
    Timer t;
    SimpleDateFormat st;

    public void times() {


        t = new Timer(0, new ActionListener() {
            @Override
            public void actionPerformed(ActionEvent e) {
               // throw new UnsupportedOperationException("Not supported yet."); //To change body of generated methods, choose Tools | Templates.
             
               Date dt = new Date();
               st = new SimpleDateFormat("hh:mm:ss a");
               String ss = st.format(dt);
               tim.setText(ss); 
            }
        });
        
        t.start();
    }
    
    private void Fill_tableDepart(){

    try{
            con = DriverManager.getConnection("jdbc:mysql://localhost/resturantmanagement","root","");
            String Quary = "SELECT `الاقسام` FROM `depart` ORDER BY `كود القسم`";
            Statement st = con.createStatement();
            rs = st.executeQuery(Quary);
            ResultSetMetaData rsmd = rs.getMetaData();
            model = (DefaultTableModel)table_depart.getModel();
            int cols = rsmd.getColumnCount();
            String[] colName = new String[cols];
            for(int i=0 ; i<cols;i++){
                colName[i] = rsmd.getColumnName(i+1);
            }
            model.setColumnIdentifiers(colName);
            String name;
            while(rs.next()){
                name = rs.getString(1);
                String[] row = {name};
                model.addRow(row);
            }
            st.close();
            con.close();
        }catch(Exception e){
            JOptionPane.showMessageDialog(this, e);
        }
    }
     private void Fill_tableOrder(){

    try{
            con = DriverManager.getConnection("jdbc:mysql://localhost/resturantmanagement","root","");
            String Quary = "SELECT * FROM `salles`";
            ps = con.prepareStatement(Quary);
            rs = ps.executeQuery();
            order_table.setModel(DbUtils.resultSetToTableModel(rs));
        }catch(Exception e){
            JOptionPane.showMessageDialog(this, e);
        }
    }
    
    private void Fill_tableSalles(){

    try{
            con = DriverManager.getConnection("jdbc:mysql://localhost/resturantmanagement","root","");
            String Quary = "SELECT * FROM `salles_screen`";
            ps = con.prepareStatement(Quary);
            rs = ps.executeQuery();
            categort_table.setModel(DbUtils.resultSetToTableModel(rs));
        }catch(Exception e){
            JOptionPane.showMessageDialog(this, e);
        }
    }
    
    public static void AddRowToTable(Object [] dataR){
    
        DefaultTableModel model =(DefaultTableModel)order_table.getModel();
        model.addRow(dataR);
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jScrollPane1 = new javax.swing.JScrollPane();
        order_table = new javax.swing.JTable();
        jButton3 = new javax.swing.JButton();
        jButton4 = new javax.swing.JButton();
        jButton5 = new javax.swing.JButton();
        jButton6 = new javax.swing.JButton();
        jButton7 = new javax.swing.JButton();
        jButton8 = new javax.swing.JButton();
        jButton9 = new javax.swing.JButton();
        jButton10 = new javax.swing.JButton();
        jButton11 = new javax.swing.JButton();
        jButton12 = new javax.swing.JButton();
        jButton13 = new javax.swing.JButton();
        jButton14 = new javax.swing.JButton();
        jButton15 = new javax.swing.JButton();
        jButton16 = new javax.swing.JButton();
        jButton17 = new javax.swing.JButton();
        jButton18 = new javax.swing.JButton();
        jButton19 = new javax.swing.JButton();
        jButton20 = new javax.swing.JButton();
        jScrollPane2 = new javax.swing.JScrollPane();
        table_depart = new javax.swing.JTable();
        jButton21 = new javax.swing.JButton();
        jButton22 = new javax.swing.JButton();
        jButton26 = new javax.swing.JButton();
        jButton27 = new javax.swing.JButton();
        jButton28 = new javax.swing.JButton();
        jScrollPane3 = new javax.swing.JScrollPane();
        categort_table = new javax.swing.JTable();
        jLabel1 = new javax.swing.JLabel();
        jLabel2 = new javax.swing.JLabel();
        jLabel3 = new javax.swing.JLabel();
        jLabel4 = new javax.swing.JLabel();
        tim = new javax.swing.JLabel();
        jLabel6 = new javax.swing.JLabel();
        history = new javax.swing.JLabel();
        jLabel8 = new javax.swing.JLabel();
        jButton29 = new javax.swing.JButton();
        jButton30 = new javax.swing.JButton();
        jButton31 = new javax.swing.JButton();
        jButton32 = new javax.swing.JButton();
        jLabel18 = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setUndecorated(true);
        getContentPane().setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        order_table.setFont(new java.awt.Font("Tahoma", 1, 22)); // NOI18N
        order_table.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {

            },
            new String [] {
                "الكمية", "اسم الصنف", "الحجم", "السعر", "الاجمالي"
            }
        ) {
            boolean[] canEdit = new boolean [] {
                false, false, false, false, false
            };

            public boolean isCellEditable(int rowIndex, int columnIndex) {
                return canEdit [columnIndex];
            }
        });
        order_table.setRowHeight(30);
        order_table.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                order_tableMouseClicked(evt);
            }
        });
        jScrollPane1.setViewportView(order_table);

        getContentPane().add(jScrollPane1, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, 70, 500, 440));

        jButton3.setBackground(new java.awt.Color(0, 102, 102));
        jButton3.setFont(new java.awt.Font("Tahoma", 1, 20)); // NOI18N
        jButton3.setForeground(new java.awt.Color(255, 255, 255));
        jButton3.setText("3");
        getContentPane().add(jButton3, new org.netbeans.lib.awtextra.AbsoluteConstraints(210, 510, 100, 55));

        jButton4.setBackground(new java.awt.Color(0, 102, 102));
        jButton4.setFont(new java.awt.Font("Tahoma", 1, 20)); // NOI18N
        jButton4.setForeground(new java.awt.Color(255, 255, 255));
        jButton4.setText("إنهاء البون");
        getContentPane().add(jButton4, new org.netbeans.lib.awtextra.AbsoluteConstraints(310, 510, 200, 55));

        jButton5.setBackground(new java.awt.Color(0, 102, 102));
        jButton5.setFont(new java.awt.Font("Tahoma", 1, 20)); // NOI18N
        jButton5.setForeground(new java.awt.Color(255, 255, 255));
        jButton5.setText("2");
        getContentPane().add(jButton5, new org.netbeans.lib.awtextra.AbsoluteConstraints(110, 510, 100, 55));

        jButton6.setBackground(new java.awt.Color(0, 102, 102));
        jButton6.setFont(new java.awt.Font("Tahoma", 1, 20)); // NOI18N
        jButton6.setForeground(new java.awt.Color(255, 255, 255));
        jButton6.setText("1");
        getContentPane().add(jButton6, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, 510, 100, 55));

        jButton7.setBackground(new java.awt.Color(0, 102, 102));
        jButton7.setFont(new java.awt.Font("Tahoma", 1, 20)); // NOI18N
        jButton7.setForeground(new java.awt.Color(255, 255, 255));
        jButton7.setText("6");
        getContentPane().add(jButton7, new org.netbeans.lib.awtextra.AbsoluteConstraints(210, 565, 100, 50));

        jButton8.setBackground(new java.awt.Color(0, 102, 102));
        jButton8.setFont(new java.awt.Font("Tahoma", 1, 20)); // NOI18N
        jButton8.setForeground(new java.awt.Color(255, 255, 255));
        jButton8.setText("5");
        getContentPane().add(jButton8, new org.netbeans.lib.awtextra.AbsoluteConstraints(110, 565, 100, 50));

        jButton9.setBackground(new java.awt.Color(0, 102, 102));
        jButton9.setFont(new java.awt.Font("Tahoma", 1, 20)); // NOI18N
        jButton9.setForeground(new java.awt.Color(255, 255, 255));
        jButton9.setText("4");
        getContentPane().add(jButton9, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, 565, 100, 50));

        jButton10.setBackground(new java.awt.Color(0, 102, 102));
        jButton10.setFont(new java.awt.Font("Tahoma", 1, 20)); // NOI18N
        jButton10.setForeground(new java.awt.Color(255, 255, 255));
        jButton10.setText("تجهيز");
        getContentPane().add(jButton10, new org.netbeans.lib.awtextra.AbsoluteConstraints(310, 565, 200, 50));

        jButton11.setBackground(new java.awt.Color(0, 102, 102));
        jButton11.setFont(new java.awt.Font("Tahoma", 1, 20)); // NOI18N
        jButton11.setForeground(new java.awt.Color(255, 255, 255));
        jButton11.setText("9");
        getContentPane().add(jButton11, new org.netbeans.lib.awtextra.AbsoluteConstraints(210, 615, 100, 50));

        jButton12.setBackground(new java.awt.Color(0, 102, 102));
        jButton12.setFont(new java.awt.Font("Tahoma", 1, 20)); // NOI18N
        jButton12.setForeground(new java.awt.Color(255, 255, 255));
        jButton12.setText("8");
        getContentPane().add(jButton12, new org.netbeans.lib.awtextra.AbsoluteConstraints(110, 615, 100, 50));

        jButton13.setBackground(new java.awt.Color(0, 102, 102));
        jButton13.setFont(new java.awt.Font("Tahoma", 1, 20)); // NOI18N
        jButton13.setForeground(new java.awt.Color(255, 255, 255));
        jButton13.setText("7");
        getContentPane().add(jButton13, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, 615, 100, 50));

        jButton14.setBackground(new java.awt.Color(0, 102, 102));
        jButton14.setFont(new java.awt.Font("Tahoma", 1, 20)); // NOI18N
        jButton14.setForeground(new java.awt.Color(255, 255, 255));
        jButton14.setText("1/8");
        getContentPane().add(jButton14, new org.netbeans.lib.awtextra.AbsoluteConstraints(310, 615, 100, 50));

        jButton15.setBackground(new java.awt.Color(0, 102, 102));
        jButton15.setFont(new java.awt.Font("Tahoma", 1, 20)); // NOI18N
        jButton15.setForeground(new java.awt.Color(255, 255, 255));
        jButton15.setText("1/4");
        getContentPane().add(jButton15, new org.netbeans.lib.awtextra.AbsoluteConstraints(410, 615, 100, 50));

        jButton16.setBackground(new java.awt.Color(0, 102, 102));
        jButton16.setFont(new java.awt.Font("Tahoma", 1, 20)); // NOI18N
        jButton16.setForeground(new java.awt.Color(255, 255, 255));
        jButton16.setText("C");
        getContentPane().add(jButton16, new org.netbeans.lib.awtextra.AbsoluteConstraints(210, 665, 100, 50));

        jButton17.setBackground(new java.awt.Color(0, 102, 102));
        jButton17.setFont(new java.awt.Font("Tahoma", 1, 20)); // NOI18N
        jButton17.setForeground(new java.awt.Color(255, 255, 255));
        jButton17.setIcon(new javax.swing.ImageIcon(getClass().getResource("/images/return.png"))); // NOI18N
        getContentPane().add(jButton17, new org.netbeans.lib.awtextra.AbsoluteConstraints(110, 665, 100, 50));

        jButton18.setBackground(new java.awt.Color(0, 102, 102));
        jButton18.setFont(new java.awt.Font("Tahoma", 1, 20)); // NOI18N
        jButton18.setForeground(new java.awt.Color(255, 255, 255));
        jButton18.setText("0");
        getContentPane().add(jButton18, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, 665, 100, 50));

        jButton19.setBackground(new java.awt.Color(0, 102, 102));
        jButton19.setFont(new java.awt.Font("Tahoma", 1, 20)); // NOI18N
        jButton19.setForeground(new java.awt.Color(255, 255, 255));
        jButton19.setText("1/2");
        getContentPane().add(jButton19, new org.netbeans.lib.awtextra.AbsoluteConstraints(310, 665, 100, 50));

        jButton20.setBackground(new java.awt.Color(0, 102, 102));
        jButton20.setFont(new java.awt.Font("Tahoma", 1, 20)); // NOI18N
        jButton20.setForeground(new java.awt.Color(255, 255, 255));
        jButton20.setText("3/4");
        getContentPane().add(jButton20, new org.netbeans.lib.awtextra.AbsoluteConstraints(410, 665, 100, 50));

        jScrollPane2.setHorizontalScrollBarPolicy(javax.swing.ScrollPaneConstants.HORIZONTAL_SCROLLBAR_NEVER);
        jScrollPane2.setHorizontalScrollBar(null);

        table_depart.setAutoCreateRowSorter(true);
        table_depart.setFont(new java.awt.Font("Tahoma", 1, 30)); // NOI18N
        table_depart.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {

            },
            new String [] {
                "الاقسام"
            }
        )

        {
            Class[] types = new Class [] {
                java.lang.String.class
            };
            boolean[] canEdit = new boolean [] {
                false
            };

            public Class getColumnClass(int columnIndex) {
                return types [columnIndex];
            }

            public boolean isCellEditable(int rowIndex, int columnIndex) {
                return canEdit [columnIndex];
            }
        });
        table_depart.setAutoscrolls(false);
        table_depart.setEditingColumn(0);
        table_depart.setEditingRow(0);
        table_depart.setGridColor(new java.awt.Color(0, 153, 153));
        table_depart.setRowHeight(50);
        table_depart.setSelectionBackground(new java.awt.Color(102, 102, 255));
        table_depart.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                table_departMouseClicked(evt);
            }
        });
        jScrollPane2.setViewportView(table_depart);

        getContentPane().add(jScrollPane2, new org.netbeans.lib.awtextra.AbsoluteConstraints(510, 71, 190, 640));

        jButton21.setBackground(new java.awt.Color(0, 102, 102));
        jButton21.setFont(new java.awt.Font("Tahoma", 1, 15)); // NOI18N
        jButton21.setForeground(new java.awt.Color(255, 255, 255));
        jButton21.setText("اوردرات الديلفري");
        jButton21.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton21ActionPerformed(evt);
            }
        });
        getContentPane().add(jButton21, new org.netbeans.lib.awtextra.AbsoluteConstraints(1080, 10, 150, 60));

        jButton22.setBackground(new java.awt.Color(0, 102, 102));
        jButton22.setFont(new java.awt.Font("Tahoma", 1, 20)); // NOI18N
        jButton22.setForeground(new java.awt.Color(255, 255, 255));
        jButton22.setText("خروج");
        jButton22.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton22ActionPerformed(evt);
            }
        });
        getContentPane().add(jButton22, new org.netbeans.lib.awtextra.AbsoluteConstraints(1230, 10, 130, 60));

        jButton26.setBackground(new java.awt.Color(0, 102, 102));
        jButton26.setFont(new java.awt.Font("Tahoma", 1, 20)); // NOI18N
        jButton26.setForeground(new java.awt.Color(255, 255, 255));
        jButton26.setIcon(new javax.swing.ImageIcon(getClass().getResource("/images/addition.png"))); // NOI18N
        jButton26.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton26ActionPerformed(evt);
            }
        });
        getContentPane().add(jButton26, new org.netbeans.lib.awtextra.AbsoluteConstraints(230, 10, 110, 50));

        jButton27.setBackground(new java.awt.Color(0, 102, 102));
        jButton27.setFont(new java.awt.Font("Tahoma", 1, 20)); // NOI18N
        jButton27.setForeground(new java.awt.Color(255, 255, 255));
        jButton27.setText("تيك اوي");
        jButton27.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton27ActionPerformed(evt);
            }
        });
        getContentPane().add(jButton27, new org.netbeans.lib.awtextra.AbsoluteConstraints(960, 10, 120, 60));

        jButton28.setBackground(new java.awt.Color(0, 102, 102));
        jButton28.setFont(new java.awt.Font("Tahoma", 1, 20)); // NOI18N
        jButton28.setForeground(new java.awt.Color(255, 255, 255));
        jButton28.setText("ديلفري");
        getContentPane().add(jButton28, new org.netbeans.lib.awtextra.AbsoluteConstraints(840, 10, 120, 60));

        categort_table.setFont(new java.awt.Font("Tahoma", 1, 24)); // NOI18N
        categort_table.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {

            },
            new String [] {
                "كود الصنف", "اسم الصنف 1", "الوحدة", "سعر التكلفة"
            }
        ) {
            boolean[] canEdit = new boolean [] {
                false, false, false, false
            };

            public boolean isCellEditable(int rowIndex, int columnIndex) {
                return canEdit [columnIndex];
            }
        });
        categort_table.setDoubleBuffered(true);
        categort_table.setEditingColumn(0);
        categort_table.setEditingRow(0);
        categort_table.setRowHeight(35);
        categort_table.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                categort_tableMouseClicked(evt);
            }
        });
        jScrollPane3.setViewportView(categort_table);

        getContentPane().add(jScrollPane3, new org.netbeans.lib.awtextra.AbsoluteConstraints(700, 70, 660, 640));

        jLabel1.setFont(new java.awt.Font("Tahoma", 1, 20)); // NOI18N
        jLabel1.setForeground(new java.awt.Color(255, 255, 255));
        jLabel1.setText("--------");
        getContentPane().add(jLabel1, new org.netbeans.lib.awtextra.AbsoluteConstraints(1160, 730, -1, 30));

        jLabel2.setFont(new java.awt.Font("Tahoma", 1, 20)); // NOI18N
        jLabel2.setForeground(new java.awt.Color(255, 255, 255));
        jLabel2.setText("رقم اليوم:");
        getContentPane().add(jLabel2, new org.netbeans.lib.awtextra.AbsoluteConstraints(1240, 730, -1, 30));

        jLabel3.setFont(new java.awt.Font("Tahoma", 1, 20)); // NOI18N
        jLabel3.setForeground(new java.awt.Color(255, 255, 255));
        jLabel3.setText("--------");
        getContentPane().add(jLabel3, new org.netbeans.lib.awtextra.AbsoluteConstraints(790, 735, 120, 30));

        jLabel4.setFont(new java.awt.Font("Tahoma", 1, 20)); // NOI18N
        jLabel4.setForeground(new java.awt.Color(255, 255, 255));
        jLabel4.setText("رقم الوردية");
        getContentPane().add(jLabel4, new org.netbeans.lib.awtextra.AbsoluteConstraints(920, 730, -1, 30));

        tim.setFont(new java.awt.Font("Tahoma", 1, 20)); // NOI18N
        tim.setForeground(new java.awt.Color(255, 255, 255));
        tim.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        tim.setText("--------");
        getContentPane().add(tim, new org.netbeans.lib.awtextra.AbsoluteConstraints(510, 730, 150, 30));

        jLabel6.setFont(new java.awt.Font("Tahoma", 1, 20)); // NOI18N
        jLabel6.setForeground(new java.awt.Color(255, 255, 255));
        jLabel6.setText("التوقيت");
        getContentPane().add(jLabel6, new org.netbeans.lib.awtextra.AbsoluteConstraints(660, 730, -1, 30));

        history.setFont(new java.awt.Font("Tahoma", 1, 20)); // NOI18N
        history.setForeground(new java.awt.Color(255, 255, 255));
        history.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        history.setText("--------");
        getContentPane().add(history, new org.netbeans.lib.awtextra.AbsoluteConstraints(120, 730, 150, 30));

        jLabel8.setFont(new java.awt.Font("Tahoma", 1, 20)); // NOI18N
        jLabel8.setForeground(new java.awt.Color(255, 255, 255));
        jLabel8.setText("التاريخ");
        getContentPane().add(jLabel8, new org.netbeans.lib.awtextra.AbsoluteConstraints(280, 730, -1, -1));

        jButton29.setBackground(new java.awt.Color(0, 102, 102));
        jButton29.setFont(new java.awt.Font("Tahoma", 1, 20)); // NOI18N
        jButton29.setForeground(new java.awt.Color(255, 255, 255));
        jButton29.setText("صالة");
        getContentPane().add(jButton29, new org.netbeans.lib.awtextra.AbsoluteConstraints(700, 10, 140, 60));

        jButton30.setBackground(new java.awt.Color(0, 102, 102));
        jButton30.setFont(new java.awt.Font("Tahoma", 1, 20)); // NOI18N
        jButton30.setForeground(new java.awt.Color(255, 255, 255));
        jButton30.setIcon(new javax.swing.ImageIcon(getClass().getResource("/images/load.png"))); // NOI18N
        jButton30.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton30ActionPerformed(evt);
            }
        });
        getContentPane().add(jButton30, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, 10, 110, 50));

        jButton31.setBackground(new java.awt.Color(0, 102, 102));
        jButton31.setFont(new java.awt.Font("Tahoma", 1, 20)); // NOI18N
        jButton31.setForeground(new java.awt.Color(255, 255, 255));
        jButton31.setIcon(new javax.swing.ImageIcon(getClass().getResource("/images/mul.png"))); // NOI18N
        jButton31.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton31ActionPerformed(evt);
            }
        });
        getContentPane().add(jButton31, new org.netbeans.lib.awtextra.AbsoluteConstraints(340, 10, 110, 50));

        jButton32.setBackground(new java.awt.Color(0, 102, 102));
        jButton32.setFont(new java.awt.Font("Tahoma", 1, 20)); // NOI18N
        jButton32.setForeground(new java.awt.Color(255, 255, 255));
        jButton32.setIcon(new javax.swing.ImageIcon(getClass().getResource("/images/sub.png"))); // NOI18N
        jButton32.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton32ActionPerformed(evt);
            }
        });
        getContentPane().add(jButton32, new org.netbeans.lib.awtextra.AbsoluteConstraints(120, 10, 110, 50));

        jLabel18.setIcon(new javax.swing.ImageIcon(getClass().getResource("/images/home-background-image.png"))); // NOI18N
        getContentPane().add(jLabel18, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 0, -1, -1));

        pack();
        setLocationRelativeTo(null);
    }// </editor-fold>//GEN-END:initComponents

    private void jButton27ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton27ActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_jButton27ActionPerformed

    private void jButton22ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton22ActionPerformed
        // TODO add your handling code here:
        dispose();
    }//GEN-LAST:event_jButton22ActionPerformed

    private void table_departMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_table_departMouseClicked
        // TODO add your handling code here:
        
         // Table Click
        categort_table.clearSelection();
       int row = this.table_depart.getSelectedRow();
       String click_row = this.table_depart.getModel().getValueAt(row, 0).toString();
       try{
            con = DriverManager.getConnection("jdbc:mysql://localhost/resturantmanagement","root","");
            String Quary = "SELECT `كود الصنف`, `اسم الصنف 1`, `الوحدة`, `سعر التكلفة` FROM `categories` where `القسم`='"+click_row+"'";
            Statement st = con.createStatement();
            rs = st.executeQuery(Quary);
            ResultSetMetaData rsmd = rs.getMetaData();
            model = (DefaultTableModel)categort_table.getModel();
            
            int cols = rsmd.getColumnCount();
            String[] colName = new String[cols];
            for(int i=0 ; i<cols;i++){
                colName[i] = rsmd.getColumnName(i+1);
            }
            model.setColumnIdentifiers(colName);
            String code , name1 , unit , price;
            while(rs.next()){
                code = rs.getString(1);
                name1 = rs.getString(2);
                unit = rs.getString(3);
                price = rs.getString(4);
                String[] row1 = {code , name1 , unit , price};
                model.addRow(row1);
            }
            //st.close();
            //con.close();
            
           // this.categort_table.setModel(DbUtils.resultSetToTableModel(rs));
       }catch(Exception e){
           JOptionPane.showMessageDialog(this, e);
       }
       new client().table_setting(this.categort_table);
    }//GEN-LAST:event_table_departMouseClicked

    private void categort_tableMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_categort_tableMouseClicked
        // TODO add your handling code here:
            // Table Click
       
        int row = this.categort_table.getSelectedRow();
        int qty = Integer.parseInt(this.categort_table.getModel().getValueAt(row, 0).toString());
        String category = this.categort_table.getModel().getValueAt(row, 1).toString();
        String volume = this.categort_table.getModel().getValueAt(row, 2).toString();
        int price = Integer.parseInt(this.categort_table.getModel().getValueAt(row, 3).toString());
        int total = price;
        
        System.out.println(qty+"\n"+category+"\n"+volume+"\n"+price+"\n"+total);
      
        try {
            con = DriverManager.getConnection("jdbc:mysql://localhost/resturantmanagement", "root", "");
            String Quary = "INSERT INTO `salles_screen`(`الكمية`, `اسم الصنف`, `الحجم`, `السعر`, `الاجمالي`) VALUES(?,?,?,?,?)";
            ps = con.prepareStatement(Quary);
            ps.setInt(1, 1);
            ps.setString(2, category);
            ps.setString(3, volume);
            ps.setInt(4, price);
            ps.setInt(5, total);
            ps.executeUpdate();
            //Fill_tableSalles();
            con.close();
            ps.close();
        } catch (Exception e) {
            JOptionPane.showMessageDialog(this, e);
        }
/*
        // Add
        try {
            con = DriverManager.getConnection("jdbc:mysql://localhost/resturantmanagement", "root", "");
            String Quary = "INSERT INTO `salles`(`الكمية`, `اسم الصنف`, `الحجم`, `السعر`, `الاجمالي`) VALUES(?,?,?,?,?)";
            ps = con.prepareStatement(Quary);
            ps.setInt(1, qty);
            ps.setString(2, str1);
            ps.setString(3, str2);
            ps.setInt(4, price);
            total = qty*price;
            ps.setInt(5, total);
            ps.executeUpdate();
            
        } catch (Exception e) {

            JOptionPane.showMessageDialog(null, e);

        }
*/

      // ScreenSalles.AddRowToTable(new Object[]{qty,str1,str2,price,total});
       
       new client().table_setting(this.categort_table);
    }//GEN-LAST:event_categort_tableMouseClicked

    private void order_tableMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_order_tableMouseClicked
        // TODO add your handling code here:
        
           // Table Click
        
       int row = this.order_table.getSelectedRow();
       qty = Integer.parseInt(this.order_table.getModel().getValueAt(row, 0).toString());
       name = this.order_table.getModel().getValueAt(row, 1).toString();
       price = Integer.parseInt(this.order_table.getModel().getValueAt(row, 3).toString());
     /*  try{
            con = DriverManager.getConnection("jdbc:mysql://localhost/resturantmanagement","root","");
            String Quary = "SELECT `الكمية`,`السعر`, `الاجمالي` FROM `salles_screen` WHERE `اسم الصنف`='"+name+"'";
            ps = con.prepareStatement(Quary);
            rs = ps.executeQuery();
            if(rs.next()){
            qty = Integer.parseInt(rs.getString("الكمية"));
            price = Integer.parseInt(rs.getString("السعر"));
            total = Integer.parseInt(rs.getString("الاجمالي"));
            System.out.println("xxxxxxxxxxxxxxxx");
            }
       }catch(Exception e){
           JOptionPane.showMessageDialog(this, e);
       } */                                        
    }//GEN-LAST:event_order_tableMouseClicked

    private void jButton21ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton21ActionPerformed
        // TODO add your handling code here:
        new Order_Delivery().setVisible(true);
    }//GEN-LAST:event_jButton21ActionPerformed

    private void jButton26ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton26ActionPerformed
        // TODO add your handling code here:
       // counter
       qty = qty + 1;
       total = price*qty;
        try{
              con = DriverManager.getConnection("jdbc:mysql://localhost/resturantmanagement", "root", "");
            String Quary = "UPDATE `salles_screen` SET `الكمية`=?,`اسم الصنف`=?,`السعر`=?,`الاجمالي`=? WHERE `اسم الصنف`='" + name + "'";
            ps = con.prepareStatement(Quary);
            ps.setInt(1, qty);
            ps.setString(2, name);
            ps.setInt(3, price);
            ps.setInt(4, total);
            ps.executeUpdate();
            Fill_tableSalles();
        }catch(Exception e){
            JOptionPane.showMessageDialog(this, e);
        }
    }//GEN-LAST:event_jButton26ActionPerformed

    private void jButton30ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton30ActionPerformed
        // TODO add your handling code here:
          // delete
        try {

            con = DriverManager.getConnection("jdbc:mysql://localhost/resturantmanagement","root","");
            String quary = "DELETE FROM `salles_screen`";
            ps = con.prepareStatement(quary);
            ps.executeUpdate();
            Fill_tableSalles();
        } catch (Exception e) {
            JOptionPane.showMessageDialog(this, e);
        }
    }//GEN-LAST:event_jButton30ActionPerformed

    private void jButton31ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton31ActionPerformed
        // TODO add your handling code here:
             // delete
           int row = this.order_table.getSelectedRow();
       name = this.order_table.getModel().getValueAt(row, 1).toString();   
        try {

            con = DriverManager.getConnection("jdbc:mysql://localhost/resturantmanagement","root","");
            String quary = "DELETE FROM `salles_screen` where `اسم الصنف`='"+name+"'";
            ps = con.prepareStatement(quary);
            ps.executeUpdate();
            Fill_tableSalles();
        } catch (Exception e) {
            JOptionPane.showMessageDialog(this, e);
        }
    }//GEN-LAST:event_jButton31ActionPerformed

    private void jButton32ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton32ActionPerformed
        // TODO add your handling code here:
        
              // counter
       if(qty>1)
             qty = qty - 1;
       else
           qty = 1;
       total = price*qty;
        try{
              con = DriverManager.getConnection("jdbc:mysql://localhost/resturantmanagement", "root", "");
            String Quary = "UPDATE `salles_screen` SET `الكمية`=?,`اسم الصنف`=?,`السعر`=?,`الاجمالي`=? WHERE `اسم الصنف`='" + name + "'";
            ps = con.prepareStatement(Quary);
            ps.setInt(1, qty);
            ps.setString(2, name);
            ps.setInt(3, price);
            ps.setInt(4, total);
            ps.executeUpdate();
            Fill_tableSalles();
        }catch(Exception e){
            JOptionPane.showMessageDialog(this, e);
        }
    }//GEN-LAST:event_jButton32ActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(ScreenSalles.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(ScreenSalles.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(ScreenSalles.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(ScreenSalles.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new ScreenSalles().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JTable categort_table;
    private javax.swing.JLabel history;
    private javax.swing.JButton jButton10;
    private javax.swing.JButton jButton11;
    private javax.swing.JButton jButton12;
    private javax.swing.JButton jButton13;
    private javax.swing.JButton jButton14;
    private javax.swing.JButton jButton15;
    private javax.swing.JButton jButton16;
    private javax.swing.JButton jButton17;
    private javax.swing.JButton jButton18;
    private javax.swing.JButton jButton19;
    private javax.swing.JButton jButton20;
    private javax.swing.JButton jButton21;
    private javax.swing.JButton jButton22;
    private javax.swing.JButton jButton26;
    private javax.swing.JButton jButton27;
    private javax.swing.JButton jButton28;
    private javax.swing.JButton jButton29;
    private javax.swing.JButton jButton3;
    private javax.swing.JButton jButton30;
    private javax.swing.JButton jButton31;
    private javax.swing.JButton jButton32;
    private javax.swing.JButton jButton4;
    private javax.swing.JButton jButton5;
    private javax.swing.JButton jButton6;
    private javax.swing.JButton jButton7;
    private javax.swing.JButton jButton8;
    private javax.swing.JButton jButton9;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel18;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel6;
    private javax.swing.JLabel jLabel8;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JScrollPane jScrollPane2;
    private javax.swing.JScrollPane jScrollPane3;
    private static javax.swing.JTable order_table;
    private javax.swing.JTable table_depart;
    private javax.swing.JLabel tim;
    // End of variables declaration//GEN-END:variables
}
