
import java.sql.Connection;
import java.sql.DriverManager;
import java.sql.PreparedStatement;
import java.sql.ResultSet;
import java.sql.ResultSetMetaData;
import java.sql.Statement;
import javax.swing.JColorChooser;
import javax.swing.JOptionPane;
import javax.swing.table.DefaultTableModel;
import net.proteanit.sql.DbUtils;

/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */

/**
 *
 * @author Mohamed_Abdeldaym
 */
public class Screen_depart extends javax.swing.JFrame {

    private Connection con = null;
    private PreparedStatement ps = null;
    private ResultSet rs = null;
    DefaultTableModel model;
    int row;
    
    public Screen_depart() {
        initComponents(); 
        Fill_table();
        set_code();
        dt1.setEnabled(false);
    }
    
    private void set_code(){
    
        int count = this.jTable1.getRowCount();
        dt1.setText(String.valueOf(count+1));
    }
    
    private void clear(){
     dt2.setText("");
    }
    
    private void Fill_table(){

    try{
            con = DriverManager.getConnection("jdbc:mysql://localhost/resturantmanagement","root","");
            Statement st = con.createStatement();
            String Quary = "SELECT * FROM `depart`";
            rs = st.executeQuery(Quary);
            ResultSetMetaData rsmd = rs.getMetaData();
            model = (DefaultTableModel)jTable1.getModel();
            int cols = rsmd.getColumnCount();
            String[] colName = new String[cols];
            for(int i=0 ; i<cols;i++){
                colName[i] = rsmd.getColumnName(i+1);
            }
            model.setColumnIdentifiers(colName);
            String code , name;
            while(rs.next()){
                code = rs.getString(1);
                name = rs.getString(2);
                String[] row = {code,name};
                model.addRow(row);
            }
            st.close();
            con.close();
        }catch(Exception e){
            JOptionPane.showMessageDialog(this, e);
        }
    new client().table_setting(this.jTable1);
    }
    
    private void Fill_tableL(){

    try{
            con = DriverManager.getConnection("jdbc:mysql://localhost/resturantmanagement","root","");
            String Quary = "SELECT * FROM `depart`";
            ps = con.prepareStatement(Quary);
            rs = ps.executeQuery();
            this.jTable1.setModel(DbUtils.resultSetToTableModel(rs));
        }catch(Exception e){
            JOptionPane.showMessageDialog(this, e);
        }
    }
    
    private void Search(){
    
        if(search1.getText().equals(""))
           this.Fill_table();
        
        else{
            try{
            con = DriverManager.getConnection("jdbc:mysql://localhost/resturantmanagement","root","");
            String Quary = "SELECT * FROM `depart` WHERE `كود القسم`='"+search1.getText()+"' or `الاقسام`='"+search1.getText()+"'";
            ps = con.prepareStatement(Quary);
            rs = ps.executeQuery();
            jTable1.setModel(DbUtils.resultSetToTableModel(rs));
        }catch(Exception e){
            JOptionPane.showMessageDialog(this, e);
        }
        }
        new client().table_setting(this.jTable1);
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        myButton11 = new MyButton();
        myButton12 = new MyButton();
        myButton13 = new MyButton();
        myButton14 = new MyButton();
        myButton15 = new MyButton();
        myButton17 = new MyButton();
        jLabel1 = new javax.swing.JLabel();
        jLabel20 = new javax.swing.JLabel();
        dt1 = new javax.swing.JTextField();
        dt2 = new javax.swing.JTextField();
        jLabel2 = new javax.swing.JLabel();
        jButton1 = new javax.swing.JButton();
        jButton2 = new javax.swing.JButton();
        search1 = new javax.swing.JTextField();
        jLabel5 = new javax.swing.JLabel();
        jScrollPane1 = new javax.swing.JScrollPane();
        jTable1 = new javax.swing.JTable();
        jLabel18 = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setUndecorated(true);
        getContentPane().setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        myButton11.setForeground(new java.awt.Color(0, 255, 0));
        myButton11.setText("خروج");
        myButton11.setBorderColor(new java.awt.Color(0, 102, 102));
        myButton11.setColor(new java.awt.Color(0, 102, 102));
        myButton11.setColorClick(new java.awt.Color(0, 153, 153));
        myButton11.setColorOver(new java.awt.Color(0, 102, 102));
        myButton11.setFont(new java.awt.Font("Tahoma", 1, 18)); // NOI18N
        myButton11.setRadius(50);
        myButton11.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                myButton11ActionPerformed(evt);
            }
        });
        getContentPane().add(myButton11, new org.netbeans.lib.awtextra.AbsoluteConstraints(1220, 30, 90, 70));

        myButton12.setForeground(new java.awt.Color(0, 255, 0));
        myButton12.setText("حذف");
        myButton12.setBorderColor(new java.awt.Color(0, 102, 102));
        myButton12.setColor(new java.awt.Color(0, 102, 102));
        myButton12.setColorClick(new java.awt.Color(0, 153, 153));
        myButton12.setColorOver(new java.awt.Color(0, 102, 102));
        myButton12.setFont(new java.awt.Font("Tahoma", 1, 18)); // NOI18N
        myButton12.setRadius(50);
        myButton12.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                myButton12ActionPerformed(evt);
            }
        });
        getContentPane().add(myButton12, new org.netbeans.lib.awtextra.AbsoluteConstraints(1120, 30, 90, 70));

        myButton13.setForeground(new java.awt.Color(0, 255, 0));
        myButton13.setText("حفظ");
        myButton13.setBorderColor(new java.awt.Color(0, 102, 102));
        myButton13.setColor(new java.awt.Color(0, 102, 102));
        myButton13.setColorClick(new java.awt.Color(0, 153, 153));
        myButton13.setColorOver(new java.awt.Color(0, 102, 102));
        myButton13.setFont(new java.awt.Font("Tahoma", 1, 18)); // NOI18N
        myButton13.setRadius(50);
        myButton13.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                myButton13ActionPerformed(evt);
            }
        });
        getContentPane().add(myButton13, new org.netbeans.lib.awtextra.AbsoluteConstraints(1020, 30, 90, 70));

        myButton14.setForeground(new java.awt.Color(0, 255, 0));
        myButton14.setText("تعديل");
        myButton14.setBorderColor(new java.awt.Color(0, 102, 102));
        myButton14.setColor(new java.awt.Color(0, 102, 102));
        myButton14.setColorClick(new java.awt.Color(0, 153, 153));
        myButton14.setColorOver(new java.awt.Color(0, 102, 102));
        myButton14.setFont(new java.awt.Font("Tahoma", 1, 18)); // NOI18N
        myButton14.setRadius(50);
        myButton14.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                myButton14ActionPerformed(evt);
            }
        });
        getContentPane().add(myButton14, new org.netbeans.lib.awtextra.AbsoluteConstraints(920, 30, 90, 70));

        myButton15.setForeground(new java.awt.Color(0, 255, 0));
        myButton15.setText("جديد");
        myButton15.setBorderColor(new java.awt.Color(0, 102, 102));
        myButton15.setColor(new java.awt.Color(0, 102, 102));
        myButton15.setColorClick(new java.awt.Color(0, 153, 153));
        myButton15.setColorOver(new java.awt.Color(0, 102, 102));
        myButton15.setFont(new java.awt.Font("Tahoma", 1, 18)); // NOI18N
        myButton15.setRadius(50);
        myButton15.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                myButton15ActionPerformed(evt);
            }
        });
        getContentPane().add(myButton15, new org.netbeans.lib.awtextra.AbsoluteConstraints(820, 30, 90, 70));

        myButton17.setForeground(new java.awt.Color(0, 255, 0));
        myButton17.setText("بحث");
        myButton17.setBorderColor(new java.awt.Color(0, 102, 102));
        myButton17.setColor(new java.awt.Color(0, 102, 102));
        myButton17.setColorClick(new java.awt.Color(0, 153, 153));
        myButton17.setColorOver(new java.awt.Color(0, 102, 102));
        myButton17.setFont(new java.awt.Font("Tahoma", 1, 18)); // NOI18N
        myButton17.setRadius(50);
        myButton17.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                myButton17ActionPerformed(evt);
            }
        });
        getContentPane().add(myButton17, new org.netbeans.lib.awtextra.AbsoluteConstraints(720, 30, 90, 70));

        jLabel1.setFont(new java.awt.Font("Tahoma", 1, 18)); // NOI18N
        jLabel1.setForeground(new java.awt.Color(255, 255, 255));
        jLabel1.setText("شاشةادخال القسم ");
        getContentPane().add(jLabel1, new org.netbeans.lib.awtextra.AbsoluteConstraints(970, 200, -1, 40));

        jLabel20.setFont(new java.awt.Font("Tahoma", 1, 18)); // NOI18N
        jLabel20.setForeground(new java.awt.Color(255, 255, 0));
        jLabel20.setText("كود القسم");
        getContentPane().add(jLabel20, new org.netbeans.lib.awtextra.AbsoluteConstraints(1210, 240, -1, 40));

        dt1.setFont(new java.awt.Font("Tahoma", 1, 18)); // NOI18N
        dt1.setHorizontalAlignment(javax.swing.JTextField.CENTER);
        getContentPane().add(dt1, new org.netbeans.lib.awtextra.AbsoluteConstraints(890, 250, 310, -1));

        dt2.setFont(new java.awt.Font("Tahoma", 1, 18)); // NOI18N
        dt2.setHorizontalAlignment(javax.swing.JTextField.CENTER);
        getContentPane().add(dt2, new org.netbeans.lib.awtextra.AbsoluteConstraints(890, 290, 310, -1));

        jLabel2.setFont(new java.awt.Font("Tahoma", 1, 18)); // NOI18N
        jLabel2.setForeground(new java.awt.Color(255, 255, 0));
        jLabel2.setText("اسم القسم");
        getContentPane().add(jLabel2, new org.netbeans.lib.awtextra.AbsoluteConstraints(1210, 290, -1, 30));

        jButton1.setBackground(new java.awt.Color(0, 153, 0));
        jButton1.setFont(new java.awt.Font("Tahoma", 1, 12)); // NOI18N
        jButton1.setForeground(new java.awt.Color(255, 255, 255));
        jButton1.setText("لون الخط");
        jButton1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton1ActionPerformed(evt);
            }
        });
        getContentPane().add(jButton1, new org.netbeans.lib.awtextra.AbsoluteConstraints(890, 330, 310, -1));

        jButton2.setBackground(new java.awt.Color(0, 153, 0));
        jButton2.setFont(new java.awt.Font("Tahoma", 1, 12)); // NOI18N
        jButton2.setForeground(new java.awt.Color(255, 255, 255));
        jButton2.setText("لون الخلفية");
        getContentPane().add(jButton2, new org.netbeans.lib.awtextra.AbsoluteConstraints(890, 360, 310, -1));

        search1.setFont(new java.awt.Font("Tahoma", 1, 16)); // NOI18N
        search1.setHorizontalAlignment(javax.swing.JTextField.CENTER);
        search1.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyReleased(java.awt.event.KeyEvent evt) {
                search1KeyReleased(evt);
            }
        });
        getContentPane().add(search1, new org.netbeans.lib.awtextra.AbsoluteConstraints(70, 30, 390, -1));

        jLabel5.setFont(new java.awt.Font("Tahoma", 1, 18)); // NOI18N
        jLabel5.setForeground(new java.awt.Color(255, 255, 0));
        jLabel5.setIcon(new javax.swing.ImageIcon(getClass().getResource("/images/search.png"))); // NOI18N
        jLabel5.setText("بحث");
        getContentPane().add(jLabel5, new org.netbeans.lib.awtextra.AbsoluteConstraints(490, 30, -1, 30));

        jTable1.setAutoCreateRowSorter(true);
        jTable1.setFont(new java.awt.Font("Tahoma", 1, 18)); // NOI18N
        jTable1.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {

            },
            new String [] {
                "كود القسم", "اسم القسم"
            }
        ) {
            boolean[] canEdit = new boolean [] {
                false, false
            };

            public boolean isCellEditable(int rowIndex, int columnIndex) {
                return canEdit [columnIndex];
            }
        });
        jTable1.setRowHeight(28);
        jTable1.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                jTable1MouseClicked(evt);
            }
        });
        jScrollPane1.setViewportView(jTable1);

        getContentPane().add(jScrollPane1, new org.netbeans.lib.awtextra.AbsoluteConstraints(30, 70, 570, 680));

        jLabel18.setIcon(new javax.swing.ImageIcon(getClass().getResource("/images/home-background-image.png"))); // NOI18N
        getContentPane().add(jLabel18, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 0, -1, -1));

        pack();
        setLocationRelativeTo(null);
    }// </editor-fold>//GEN-END:initComponents

    private void myButton11ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_myButton11ActionPerformed
        // TODO add your handling code here:
        dispose();
    }//GEN-LAST:event_myButton11ActionPerformed

    private void search1KeyReleased(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_search1KeyReleased
        // TODO add your handling code here:
        Search();
    }//GEN-LAST:event_search1KeyReleased

    private void jTable1MouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jTable1MouseClicked
        // TODO add your handling code here:
       // Table Click
        
       row = this.jTable1.getSelectedRow();
       String click_row = this.jTable1.getModel().getValueAt(row, 0).toString();
       try{
            con = DriverManager.getConnection("jdbc:mysql://localhost/resturantmanagement","root","");
            String Quary = "SELECT * FROM `depart` WHERE `كود القسم` = '"+click_row+"'";
            Statement st = con.createStatement();
            rs = st.executeQuery(Quary);
            ResultSetMetaData rsmd = rs.getMetaData();
            DefaultTableModel model = (DefaultTableModel)jTable1.getModel();
            int cols = rsmd.getColumnCount();
            String[] colName = new String[cols];
            for(int i=0 ; i<cols;i++){
                colName[i] = rsmd.getColumnName(i+1);
            }
            model.setColumnIdentifiers(colName);
            String code , name;
            if(rs.next()){
                dt1.setText(rs.getString(1));
                dt2.setText(rs.getString(2));
            }
            st.close();
            con.close();
            new client().table_setting(this.jTable1);
       }catch(Exception e){
           JOptionPane.showMessageDialog(this, e);
       }
    }//GEN-LAST:event_jTable1MouseClicked

    private void jButton1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton1ActionPerformed
        // TODO add your handling code here:
        JColorChooser ch = new JColorChooser();
    }//GEN-LAST:event_jButton1ActionPerformed

    private void myButton12ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_myButton12ActionPerformed
        // TODO add your handling code here:
       
           // Delete
        try{
             con = DriverManager.getConnection("jdbc:mysql://localhost/resturantmanagement","root","");
             String Quary = "DELETE FROM `depart` WHERE `كود القسم` =?";
             ps = con.prepareStatement(Quary);
             ps.setString(1, dt1.getText());
             ps.executeUpdate();          
             clear();
             model.removeRow(row);
             set_code();
        }catch(Exception e){
            JOptionPane.showMessageDialog(this, e);
        }
    }//GEN-LAST:event_myButton12ActionPerformed

    private void myButton13ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_myButton13ActionPerformed
        // TODO add your handling code here:
        
          // Add
        try{
             con = DriverManager.getConnection("jdbc:mysql://localhost/resturantmanagement","root","");
             String Quary = "INSERT INTO `depart`(`كود القسم`, `الاقسام`)VALUES(?,?)";
             ps = con.prepareStatement(Quary);
             ps.setString(1, dt1.getText());
             ps.setString(2, dt2.getText());
             ps.executeUpdate();
             clear();
             String[]rowData = {dt1.getText(),dt2.getText()};
             model.addRow(rowData);
             set_code();
             new client().table_setting(this.jTable1);
        }catch(Exception e){
        
            JOptionPane.showMessageDialog(null, "<html><h3> هناك تكرار في الاضافة</h3></html>");
        
        }
    }//GEN-LAST:event_myButton13ActionPerformed

    private void myButton15ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_myButton15ActionPerformed
        // TODO add your handling code here:
        clear();
        set_code();
    }//GEN-LAST:event_myButton15ActionPerformed

    private void myButton17ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_myButton17ActionPerformed
        // TODO add your handling code here:
        search1.requestFocus();
    }//GEN-LAST:event_myButton17ActionPerformed

    private void myButton14ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_myButton14ActionPerformed
        // TODO add your handling code here:
               // Update
        try{
               con = DriverManager.getConnection("jdbc:mysql://localhost/resturantmanagement","root","");
               String Quary = "UPDATE `depart` SET `كود القسم`=?,`الاقسام`=? WHERE `كود القسم` = '"+dt1.getText()+"'";
               ps = con.prepareStatement(Quary);
               ps.setString(1, dt1.getText());
               ps.setString(2, dt2.getText());
               ps.executeUpdate();
               clear();
               //Fill_table();
               set_code();
        }catch(Exception e){
            JOptionPane.showMessageDialog(this, e);
        }
    }//GEN-LAST:event_myButton14ActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(Screen_depart.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(Screen_depart.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(Screen_depart.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(Screen_depart.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new Screen_depart().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JTextField dt1;
    private javax.swing.JTextField dt2;
    private javax.swing.JButton jButton1;
    private javax.swing.JButton jButton2;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel18;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel20;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JTable jTable1;
    private MyButton myButton11;
    private MyButton myButton12;
    private MyButton myButton13;
    private MyButton myButton14;
    private MyButton myButton15;
    private MyButton myButton17;
    private javax.swing.JTextField search1;
    // End of variables declaration//GEN-END:variables
}
