

import java.sql.*;
import javax.swing.JOptionPane;
import net.proteanit.sql.DbUtils;


/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */

/**
 *
 * @author Mohamed_Abdeldaym
 */
public class Screen_Delivery extends javax.swing.JFrame {


    private Connection con = null;
    private PreparedStatement ps = null;
    private ResultSet rs = null;
    
    
    public Screen_Delivery() {
        initComponents();
        this.Fill_table_d();
        jTable1.setAutoCreateRowSorter(true); 
        new client().table_setting(this.jTable1);
        dt1.setEnabled(false);
        set_code();
    }
    
   
    
    private void clear(){
        dt2.setText("");
        dt3.setText("");
        dt4.setText("");
        dt5.setText("");
        dt6.setText("");
        dt7.setText("");
        dt8.setText("");
        dt9.setText("");
        dt10.setText("");
        dt11.setText("");
        dt12.setText("");
        dt13.setText("");
        dt14.setText("");  
    }
    
    private void Fill_table_d(){

    try{
            con = DriverManager.getConnection("jdbc:mysql://localhost/resturantmanagement","root","");
            String Quary = "SELECT `الكود`, `اسم العميل`, `المنطقة`, `المنزل`, `الدور`, `1هاتف`, `هاتف2`, `هاتف3`, `هاتف4`, `الشارع`, `الشقة`FROM `delivery`";
            ps = con.prepareStatement(Quary);
            //ps.setString(1, dt1.getText());
            rs = ps.executeQuery();
            jTable1.setModel(DbUtils.resultSetToTableModel(rs));
        }catch(Exception e){
            JOptionPane.showMessageDialog(this, e);
        }
    new client().table_setting(this.jTable1);
    }
    
     private void set_code(){
    
        int count = this.jTable1.getRowCount();
        dt1.setText(String.valueOf(count+1));
    }
    
    private void Search(){
    
        if(searchd.getText().equals(""))
           this.Fill_table_d();
        
        else{
            try{
            con = DriverManager.getConnection("jdbc:mysql://localhost/resturantmanagement","root","");
            String Quary = "SELECT `الكود`, `اسم العميل`, `المنطقة`, `المنزل`, `الدور`, `1هاتف`, `هاتف2`, `هاتف3`, `هاتف4`, `الشارع`, `الشقة` FROM `delivery` WHERE `الكود`='"+searchd.getText()+"' or `اسم العميل`='"+searchd.getText()+"'";
            ps = con.prepareStatement(Quary);
            rs = ps.executeQuery();
            jTable1.setModel(DbUtils.resultSetToTableModel(rs));
        }catch(Exception e){
            JOptionPane.showMessageDialog(this, e);
        }
        }
        new client().table_setting(this.jTable1);
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        myButton11 = new MyButton();
        myButton12 = new MyButton();
        myButton13 = new MyButton();
        myButton15 = new MyButton();
        myButton17 = new MyButton();
        jLabel20 = new javax.swing.JLabel();
        dt6 = new javax.swing.JTextField();
        jLabel3 = new javax.swing.JLabel();
        dt14 = new javax.swing.JTextField();
        jLabel21 = new javax.swing.JLabel();
        dt1 = new javax.swing.JTextField();
        jLabel5 = new javax.swing.JLabel();
        dt3 = new javax.swing.JTextField();
        jLabel6 = new javax.swing.JLabel();
        dt4 = new javax.swing.JTextField();
        jLabel9 = new javax.swing.JLabel();
        dt5 = new javax.swing.JTextField();
        jLabel10 = new javax.swing.JLabel();
        dt13 = new javax.swing.JTextField();
        jLabel8 = new javax.swing.JLabel();
        searchd = new javax.swing.JTextField();
        jScrollPane1 = new javax.swing.JScrollPane();
        jTable1 = new javax.swing.JTable();
        dt2 = new javax.swing.JTextField();
        jLabel22 = new javax.swing.JLabel();
        jLabel26 = new javax.swing.JLabel();
        dt12 = new javax.swing.JTextField();
        jLabel27 = new javax.swing.JLabel();
        dt7 = new javax.swing.JTextField();
        jLabel11 = new javax.swing.JLabel();
        dt9 = new javax.swing.JTextField();
        jLabel12 = new javax.swing.JLabel();
        dt10 = new javax.swing.JTextField();
        jLabel16 = new javax.swing.JLabel();
        dt11 = new javax.swing.JTextField();
        dt8 = new javax.swing.JTextField();
        jLabel28 = new javax.swing.JLabel();
        jLabel18 = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setUndecorated(true);
        getContentPane().setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        myButton11.setForeground(new java.awt.Color(0, 255, 0));
        myButton11.setText("خروج");
        myButton11.setBorderColor(new java.awt.Color(0, 102, 102));
        myButton11.setColor(new java.awt.Color(0, 102, 102));
        myButton11.setColorClick(new java.awt.Color(0, 153, 153));
        myButton11.setColorOver(new java.awt.Color(0, 102, 102));
        myButton11.setFont(new java.awt.Font("Tahoma", 1, 18)); // NOI18N
        myButton11.setRadius(15);
        myButton11.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                myButton11ActionPerformed(evt);
            }
        });
        getContentPane().add(myButton11, new org.netbeans.lib.awtextra.AbsoluteConstraints(950, 30, 140, 70));

        myButton12.setForeground(new java.awt.Color(0, 255, 0));
        myButton12.setText("متابعة اخر اوردر");
        myButton12.setBorderColor(new java.awt.Color(0, 102, 102));
        myButton12.setColor(new java.awt.Color(0, 102, 102));
        myButton12.setColorClick(new java.awt.Color(0, 153, 153));
        myButton12.setColorOver(new java.awt.Color(0, 102, 102));
        myButton12.setFont(new java.awt.Font("Tahoma", 1, 18)); // NOI18N
        myButton12.setRadius(15);
        myButton12.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                myButton12ActionPerformed(evt);
            }
        });
        getContentPane().add(myButton12, new org.netbeans.lib.awtextra.AbsoluteConstraints(450, 30, 190, 70));

        myButton13.setForeground(new java.awt.Color(0, 255, 0));
        myButton13.setText("حفظ");
        myButton13.setBorderColor(new java.awt.Color(0, 102, 102));
        myButton13.setColor(new java.awt.Color(0, 102, 102));
        myButton13.setColorClick(new java.awt.Color(0, 153, 153));
        myButton13.setColorOver(new java.awt.Color(0, 102, 102));
        myButton13.setFont(new java.awt.Font("Tahoma", 1, 18)); // NOI18N
        myButton13.setRadius(15);
        myButton13.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                myButton13ActionPerformed(evt);
            }
        });
        getContentPane().add(myButton13, new org.netbeans.lib.awtextra.AbsoluteConstraints(800, 30, 140, 70));

        myButton15.setForeground(new java.awt.Color(0, 255, 0));
        myButton15.setText("عنوان جديد");
        myButton15.setBorderColor(new java.awt.Color(0, 102, 102));
        myButton15.setColor(new java.awt.Color(0, 102, 102));
        myButton15.setColorClick(new java.awt.Color(0, 153, 153));
        myButton15.setColorOver(new java.awt.Color(0, 102, 102));
        myButton15.setFont(new java.awt.Font("Tahoma", 1, 18)); // NOI18N
        myButton15.setRadius(15);
        myButton15.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                myButton15ActionPerformed(evt);
            }
        });
        getContentPane().add(myButton15, new org.netbeans.lib.awtextra.AbsoluteConstraints(650, 30, 140, 70));

        myButton17.setForeground(new java.awt.Color(0, 255, 0));
        myButton17.setText("استيراد");
        myButton17.setBorderColor(new java.awt.Color(0, 102, 102));
        myButton17.setColor(new java.awt.Color(0, 102, 102));
        myButton17.setColorClick(new java.awt.Color(0, 153, 153));
        myButton17.setColorOver(new java.awt.Color(0, 102, 102));
        myButton17.setFont(new java.awt.Font("Tahoma", 1, 18)); // NOI18N
        myButton17.setRadius(15);
        myButton17.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                myButton17ActionPerformed(evt);
            }
        });
        getContentPane().add(myButton17, new org.netbeans.lib.awtextra.AbsoluteConstraints(300, 30, 140, 70));

        jLabel20.setFont(new java.awt.Font("Tahoma", 1, 18)); // NOI18N
        jLabel20.setForeground(new java.awt.Color(255, 255, 255));
        jLabel20.setText("علامة مميزة");
        getContentPane().add(jLabel20, new org.netbeans.lib.awtextra.AbsoluteConstraints(1020, 310, -1, 40));

        dt6.setFont(new java.awt.Font("Tahoma", 1, 18)); // NOI18N
        dt6.setHorizontalAlignment(javax.swing.JTextField.CENTER);
        getContentPane().add(dt6, new org.netbeans.lib.awtextra.AbsoluteConstraints(730, 320, 280, -1));

        jLabel3.setFont(new java.awt.Font("Tahoma", 1, 18)); // NOI18N
        jLabel3.setForeground(new java.awt.Color(255, 255, 255));
        jLabel3.setText("سعر التكلفة");
        getContentPane().add(jLabel3, new org.netbeans.lib.awtextra.AbsoluteConstraints(1020, 400, -1, -1));

        dt14.setFont(new java.awt.Font("Tahoma", 1, 18)); // NOI18N
        dt14.setHorizontalAlignment(javax.swing.JTextField.CENTER);
        getContentPane().add(dt14, new org.netbeans.lib.awtextra.AbsoluteConstraints(370, 400, 640, -1));

        jLabel21.setFont(new java.awt.Font("Tahoma", 1, 18)); // NOI18N
        jLabel21.setForeground(new java.awt.Color(255, 255, 255));
        jLabel21.setText("الكود");
        getContentPane().add(jLabel21, new org.netbeans.lib.awtextra.AbsoluteConstraints(1020, 160, -1, 40));

        dt1.setFont(new java.awt.Font("Tahoma", 1, 18)); // NOI18N
        dt1.setHorizontalAlignment(javax.swing.JTextField.CENTER);
        getContentPane().add(dt1, new org.netbeans.lib.awtextra.AbsoluteConstraints(730, 170, 280, -1));

        jLabel5.setFont(new java.awt.Font("Tahoma", 1, 18)); // NOI18N
        jLabel5.setForeground(new java.awt.Color(255, 255, 255));
        jLabel5.setText("المنطقة");
        getContentPane().add(jLabel5, new org.netbeans.lib.awtextra.AbsoluteConstraints(1020, 230, -1, 30));

        dt3.setFont(new java.awt.Font("Tahoma", 1, 18)); // NOI18N
        dt3.setHorizontalAlignment(javax.swing.JTextField.CENTER);
        getContentPane().add(dt3, new org.netbeans.lib.awtextra.AbsoluteConstraints(730, 230, 280, -1));

        jLabel6.setFont(new java.awt.Font("Tahoma", 1, 18)); // NOI18N
        jLabel6.setForeground(new java.awt.Color(255, 255, 255));
        jLabel6.setText("المنزل");
        getContentPane().add(jLabel6, new org.netbeans.lib.awtextra.AbsoluteConstraints(1020, 260, -1, -1));

        dt4.setFont(new java.awt.Font("Tahoma", 1, 18)); // NOI18N
        dt4.setHorizontalAlignment(javax.swing.JTextField.CENTER);
        getContentPane().add(dt4, new org.netbeans.lib.awtextra.AbsoluteConstraints(730, 260, 280, -1));

        jLabel9.setFont(new java.awt.Font("Tahoma", 1, 18)); // NOI18N
        jLabel9.setForeground(new java.awt.Color(255, 255, 255));
        jLabel9.setText("الدور");
        getContentPane().add(jLabel9, new org.netbeans.lib.awtextra.AbsoluteConstraints(1020, 290, -1, 30));

        dt5.setFont(new java.awt.Font("Tahoma", 1, 18)); // NOI18N
        dt5.setHorizontalAlignment(javax.swing.JTextField.CENTER);
        getContentPane().add(dt5, new org.netbeans.lib.awtextra.AbsoluteConstraints(730, 290, 280, -1));

        jLabel10.setFont(new java.awt.Font("Tahoma", 1, 18)); // NOI18N
        jLabel10.setForeground(new java.awt.Color(255, 255, 255));
        jLabel10.setText("ملاحظات");
        getContentPane().add(jLabel10, new org.netbeans.lib.awtextra.AbsoluteConstraints(1020, 360, -1, 30));

        dt13.setFont(new java.awt.Font("Tahoma", 1, 18)); // NOI18N
        dt13.setHorizontalAlignment(javax.swing.JTextField.CENTER);
        getContentPane().add(dt13, new org.netbeans.lib.awtextra.AbsoluteConstraints(370, 360, 640, -1));

        jLabel8.setFont(new java.awt.Font("Tahoma", 1, 18)); // NOI18N
        jLabel8.setForeground(new java.awt.Color(255, 255, 255));
        jLabel8.setIcon(new javax.swing.ImageIcon(getClass().getResource("/images/search.png"))); // NOI18N
        jLabel8.setText("بحث");
        getContentPane().add(jLabel8, new org.netbeans.lib.awtextra.AbsoluteConstraints(1020, 440, 90, 30));

        searchd.setFont(new java.awt.Font("Tahoma", 1, 16)); // NOI18N
        searchd.setHorizontalAlignment(javax.swing.JTextField.CENTER);
        searchd.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyReleased(java.awt.event.KeyEvent evt) {
                searchdKeyReleased(evt);
            }
        });
        getContentPane().add(searchd, new org.netbeans.lib.awtextra.AbsoluteConstraints(370, 440, 640, -1));

        jTable1.setFont(new java.awt.Font("Tahoma", 1, 18)); // NOI18N
        jTable1.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {

            },
            new String [] {
                "الكود", "اسم العميل", "المنطقة", "المنزل", "الدور", "الشارع", "الشقة", "هاتف1", "هاتف2", "هاتف3", "هاتف4"
            }
        ) {
            boolean[] canEdit = new boolean [] {
                false, false, false, false, false, false, false, false, false, false, false
            };

            public boolean isCellEditable(int rowIndex, int columnIndex) {
                return canEdit [columnIndex];
            }
        });
        jTable1.setRowHeight(28);
        jTable1.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                jTable1MouseClicked(evt);
            }
        });
        jScrollPane1.setViewportView(jTable1);

        getContentPane().add(jScrollPane1, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, 490, 1340, 270));

        dt2.setFont(new java.awt.Font("Tahoma", 1, 18)); // NOI18N
        dt2.setHorizontalAlignment(javax.swing.JTextField.CENTER);
        getContentPane().add(dt2, new org.netbeans.lib.awtextra.AbsoluteConstraints(730, 200, 280, -1));

        jLabel22.setFont(new java.awt.Font("Tahoma", 1, 18)); // NOI18N
        jLabel22.setForeground(new java.awt.Color(255, 255, 255));
        jLabel22.setText("اسم العميل");
        getContentPane().add(jLabel22, new org.netbeans.lib.awtextra.AbsoluteConstraints(1020, 190, -1, 40));

        jLabel26.setFont(new java.awt.Font("Tahoma", 1, 18)); // NOI18N
        jLabel26.setForeground(new java.awt.Color(255, 255, 255));
        jLabel26.setText("الشقة");
        getContentPane().add(jLabel26, new org.netbeans.lib.awtextra.AbsoluteConstraints(660, 320, -1, 30));

        dt12.setFont(new java.awt.Font("Tahoma", 1, 18)); // NOI18N
        dt12.setHorizontalAlignment(javax.swing.JTextField.CENTER);
        getContentPane().add(dt12, new org.netbeans.lib.awtextra.AbsoluteConstraints(370, 320, 280, -1));

        jLabel27.setFont(new java.awt.Font("Tahoma", 1, 18)); // NOI18N
        jLabel27.setForeground(new java.awt.Color(255, 255, 255));
        jLabel27.setText("هاتف1");
        getContentPane().add(jLabel27, new org.netbeans.lib.awtextra.AbsoluteConstraints(660, 160, -1, 40));

        dt7.setFont(new java.awt.Font("Tahoma", 1, 18)); // NOI18N
        dt7.setHorizontalAlignment(javax.swing.JTextField.CENTER);
        getContentPane().add(dt7, new org.netbeans.lib.awtextra.AbsoluteConstraints(370, 170, 280, -1));

        jLabel11.setFont(new java.awt.Font("Tahoma", 1, 18)); // NOI18N
        jLabel11.setForeground(new java.awt.Color(255, 255, 255));
        jLabel11.setText("هاتف3");
        getContentPane().add(jLabel11, new org.netbeans.lib.awtextra.AbsoluteConstraints(660, 230, -1, 30));

        dt9.setFont(new java.awt.Font("Tahoma", 1, 18)); // NOI18N
        dt9.setHorizontalAlignment(javax.swing.JTextField.CENTER);
        getContentPane().add(dt9, new org.netbeans.lib.awtextra.AbsoluteConstraints(370, 230, 280, -1));

        jLabel12.setFont(new java.awt.Font("Tahoma", 1, 18)); // NOI18N
        jLabel12.setForeground(new java.awt.Color(255, 255, 255));
        jLabel12.setText("هاتف4");
        getContentPane().add(jLabel12, new org.netbeans.lib.awtextra.AbsoluteConstraints(660, 260, -1, 30));

        dt10.setFont(new java.awt.Font("Tahoma", 1, 18)); // NOI18N
        dt10.setHorizontalAlignment(javax.swing.JTextField.CENTER);
        getContentPane().add(dt10, new org.netbeans.lib.awtextra.AbsoluteConstraints(370, 260, 280, -1));

        jLabel16.setFont(new java.awt.Font("Tahoma", 1, 18)); // NOI18N
        jLabel16.setForeground(new java.awt.Color(255, 255, 255));
        jLabel16.setText("الشارع");
        getContentPane().add(jLabel16, new org.netbeans.lib.awtextra.AbsoluteConstraints(660, 290, -1, 30));

        dt11.setFont(new java.awt.Font("Tahoma", 1, 18)); // NOI18N
        dt11.setHorizontalAlignment(javax.swing.JTextField.CENTER);
        getContentPane().add(dt11, new org.netbeans.lib.awtextra.AbsoluteConstraints(370, 290, 280, -1));

        dt8.setFont(new java.awt.Font("Tahoma", 1, 18)); // NOI18N
        dt8.setHorizontalAlignment(javax.swing.JTextField.CENTER);
        getContentPane().add(dt8, new org.netbeans.lib.awtextra.AbsoluteConstraints(370, 200, 280, -1));

        jLabel28.setFont(new java.awt.Font("Tahoma", 1, 18)); // NOI18N
        jLabel28.setForeground(new java.awt.Color(255, 255, 255));
        jLabel28.setText("هاتف2");
        getContentPane().add(jLabel28, new org.netbeans.lib.awtextra.AbsoluteConstraints(660, 190, -1, 40));

        jLabel18.setIcon(new javax.swing.ImageIcon(getClass().getResource("/images/home-background-image.png"))); // NOI18N
        getContentPane().add(jLabel18, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 0, -1, -1));

        pack();
        setLocationRelativeTo(null);
    }// </editor-fold>//GEN-END:initComponents

    private void myButton11ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_myButton11ActionPerformed
        // TODO add your handling code here:
        dispose();
    }//GEN-LAST:event_myButton11ActionPerformed

    private void searchdKeyReleased(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_searchdKeyReleased
        // TODO add your handling code here:
        Search();
    }//GEN-LAST:event_searchdKeyReleased

    private void jTable1MouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jTable1MouseClicked
        // TODO add your handling code here:
     
    }//GEN-LAST:event_jTable1MouseClicked

    private void myButton12ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_myButton12ActionPerformed
        // TODO add your handling code here:
        new Order_Delivery().setVisible(true);
        dispose();
    }//GEN-LAST:event_myButton12ActionPerformed

    private void myButton13ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_myButton13ActionPerformed
        // TODO add your handling code here:
        
            // Add
            if(dt1.getText().isEmpty()||dt2.getText().isEmpty()||dt3.getText().isEmpty()||dt4.getText().isEmpty()
                || dt5.getText().isEmpty()||dt6.getText().isEmpty()||dt7.getText().isEmpty()||dt8.getText().isEmpty()
                || dt9.getText().isEmpty()||dt10.getText().isEmpty()||dt11.getText().isEmpty()||dt12.getText().isEmpty())
            {
                JOptionPane.showMessageDialog(null, "يرجي استكمال البيانات");
            }else{
        try{
             con = DriverManager.getConnection("jdbc:mysql://localhost/resturantmanagement","root","");
             String Quary = "INSERT INTO `delivery`(`الكود`, `اسم العميل`, `المنطقة`, `المنزل`, `الدور`, `علامة مميزة`, `1هاتف`, `هاتف2`, `هاتف3`, `هاتف4`, `الشارع`, `الشقة`, `ملاحظات`, `سعر التكلفة`) "
                     + "VALUES(?,?,?,?,?,?,?,?,?,?,?,?,?,?)";
             ps = con.prepareStatement(Quary);
             ps.setInt(1, Integer.parseInt(dt1.getText()));
             ps.setString(2, dt2.getText());
             ps.setString(3, dt3.getText());
             ps.setString(4, dt4.getText());
             ps.setString(5, dt5.getText());
             ps.setString(6, dt6.getText());
             ps.setString(7, dt7.getText());
             ps.setString(8, dt8.getText());
             ps.setString(9, dt9.getText());
             ps.setString(10, dt10.getText());
             ps.setString(11, dt11.getText());
             ps.setString(12, dt12.getText());
             ps.setString(13, dt13.getText());
             ps.setInt(14, Integer.parseInt(dt14.getText()));
             ps.executeUpdate();
             clear();
             this.Fill_table_d();
             set_code();
        }catch(Exception e){
        
            JOptionPane.showMessageDialog(this, e);
        
        }
            }
    }//GEN-LAST:event_myButton13ActionPerformed

    private void myButton15ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_myButton15ActionPerformed
        // TODO add your handling code here:
        clear();
        set_code();
    }//GEN-LAST:event_myButton15ActionPerformed

    private void myButton17ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_myButton17ActionPerformed
        // TODO add your handling code here:
        
    }//GEN-LAST:event_myButton17ActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(categories.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(categories.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(categories.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(categories.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new Screen_Delivery().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JTextField dt1;
    private javax.swing.JTextField dt10;
    private javax.swing.JTextField dt11;
    private javax.swing.JTextField dt12;
    private javax.swing.JTextField dt13;
    private javax.swing.JTextField dt14;
    private javax.swing.JTextField dt2;
    private javax.swing.JTextField dt3;
    private javax.swing.JTextField dt4;
    private javax.swing.JTextField dt5;
    private javax.swing.JTextField dt6;
    private javax.swing.JTextField dt7;
    private javax.swing.JTextField dt8;
    private javax.swing.JTextField dt9;
    private javax.swing.JLabel jLabel10;
    private javax.swing.JLabel jLabel11;
    private javax.swing.JLabel jLabel12;
    private javax.swing.JLabel jLabel16;
    private javax.swing.JLabel jLabel18;
    private javax.swing.JLabel jLabel20;
    private javax.swing.JLabel jLabel21;
    private javax.swing.JLabel jLabel22;
    private javax.swing.JLabel jLabel26;
    private javax.swing.JLabel jLabel27;
    private javax.swing.JLabel jLabel28;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JLabel jLabel6;
    private javax.swing.JLabel jLabel8;
    private javax.swing.JLabel jLabel9;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JTable jTable1;
    private MyButton myButton11;
    private MyButton myButton12;
    private MyButton myButton13;
    private MyButton myButton15;
    private MyButton myButton17;
    private javax.swing.JTextField searchd;
    // End of variables declaration//GEN-END:variables
}
